### ISSUE TITLE
npm install orbit-db ERROR

### ISSUE THREAD

**Issue by mourad96** [orbitdb/orbit-db#1052]
Hello,
I got an error everytime I try to install orbit-db

PS D:\React_app\orbitdb-getting-started> npm install orbit-db
npm WARN deprecated multibase@0.7.0: This module has been superseded by the multiformats module
npm WARN deprecated multibase@0.7.0: This module has been superseded by the multiformats module
npm WARN deprecated multibase@4.0.6: This module has been superseded by the multiformats module
npm WARN deprecated multibase@3.1.2: This module has been superseded by the multiformats module
npm WARN deprecated multihashing-async@0.6.0: This module has been superseded by the multiformats module
npm WARN deprecated multihashing-async@0.5.2: This module has been superseded by the multiformats module
npm WARN deprecated libp2p-crypto-secp256k1@0.3.1: Included in libp2p-crypto, use it instead. https://github.com/libp2p/js-libp2p-crypto 
npm WARN deprecated protons@1.2.1: This module is no longer maintained
npm ERR! code 1
npm ERR! path D:\React_app\orbitdb-getting-started\node_modules\go-ipfs
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node src/post-install.js
npm ERR! https://dist.ipfs.tech/go-ipfs/versions
npm ERR! Found C:\Users\envy\AppData\Local\npm-go-ipfs\Cache\go-ipfs_v0.17.0_windows-amd64.zip
npm ERR! Verifying go-ipfs_v0.17.0_windows-amd64.zip.sha512
npm ERR! OK (841e3cd4a7178d990f6047c16b14e0884af0ecd24a358d58287bda2feaacabb39e0121c9e4fc9e679a52b11eab65c317ce85de0ba631661fbb22d2df8a876338)
npm ERR! Unpacked D:\React_app\orbitdb-getting-started\node_modules\go-ipfs
npm ERR! Linking D:\React_app\orbitdb-getting-started\node_modules\go-ipfs\go-ipfs\ipfs.exe to D:\React_app\orbitdb-getting-started\node_modules\go-ipfs\bin\ipfs.exe
npm ERR! Error: EPERM: operation not permitted, symlink 'D:\React_app\orbitdb-getting-started\node_modules\go-ipfs\go-ipfs\ipfs.exe' -> 'D:\React_app\orbitdb-getting-started\node_modules\go-ipfs\bin\ipfs.exe'
npm ERR!     at Object.symlinkSync (node:fs:1655:3)
npm ERR!     at link (D:\React_app\orbitdb-getting-started\node_modules\go-ipfs\src\download.js:207:6)
npm ERR!     at module.exports (D:\React_app\orbitdb-getting-started\node_modules\go-ipfs\src\download.js:248:10)
npm ERR!     at runMicrotasks (<anonymous>)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
npm ERR!   errno: -4048,
npm ERR!   syscall: 'symlink',
npm ERR!   code: 'EPERM',
npm ERR!   path: 'D:\\React_app\\orbitdb-getting-started\\node_modules\\go-ipfs\\go-ipfs\\ipfs.exe',
npm ERR!   dest: 'D:\\React_app\\orbitdb-getting-started\\node_modules\\go-ipfs\\bin\\ipfs.exe'
npm ERR! }

--------------------------

I'm using Windows
npm -v      9.3.1
node -v     v16.14.2

**Comment by mourad96** [comment]
Running Powershell as administrator solves the problem
