### ISSUE TITLE
Error creating OrbitDB

### ISSUE THREAD

**Issue by rkyleg** [orbitdb/orbit-db#211]
I am getting this error now when creating an OrbitDB instance. I have updated to the latest version and re-installed npm modules after removing the directory. I am using the browser daemon and have tried both the IPFS signal server and a local signal server.
```
TypeError: this._daemon.load is not a function
    at _daemon.config.set (http://localhost:8100/build/main.js:211063:30)
    at http://localhost:8100/build/main.js:221933:9
    at IDBTransaction.tx.oncomplete (http://localhost:8100/build/main.js:149063:5)
    at IDBTransaction.n [as _oncomplete] (http://localhost:8100/build/polyfills.js:2:27340)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:10284)
    at Object.onInvokeTask (http://localhost:8100/build/main.js:57608:37)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:10220)
    at e.runTask (http://localhost:8100/build/polyfills.js:3:7637)
    at IDBTransaction.invoke (http://localhost:8100/build/polyfills.js:3:11397)
```

**Comment by rkyleg** [comment]
Looks like the API for creating a new IPFS instance has changed in this commit on March 15th. 

https://github.com/ipfs/js-ipfs/commit/cd906cde08ae8e9942eebcb47778defde62723d8

**Comment by rkyleg** [comment]
I had installed a newer version of ipfs, but after reinstalling ipfs-daemon, I get this error:

```
Unhandled rejection: TypeError: cb is not a function
    at http://localhost:8100/build/main.js:103381:7
    at http://localhost:8100/build/main.js:250745:5
    at more (http://localhost:8100/build/main.js:50268:7)
    at reader (http://localhost:8100/build/main.js:50317:5)
    at pull (http://localhost:8100/build/main.js:148959:14)
    at http://localhost:8100/build/main.js:148940:22
    at Function.consume.resolve.consume.ready.consume.start (http://localhost:8100/build/main.js:103089:14)
    at http://localhost:8100/build/main.js:128453:11
    at http://localhost:8100/build/main.js:128547:16
    at callListener (http://localhost:8100/build/main.js:182288:19)
    at endMicroTickScope (http://localhost:8100/build/main.js:182377:25)
    at IDBTransaction.<anonymous> (http://localhost:8100/build/main.js:182463:30)
    at IDBTransaction.n [as _oncomplete] (http://localhost:8100/build/polyfills.js:2:27340)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:10284)
    at Object.onInvokeTask (http://localhost:8100/build/main.js:57072:37)
```

**Comment by rkyleg** [comment]
seems to be working now after clearing everything out.
