### ISSUE TITLE
Create docstore errors

### ISSUE THREAD

**Issue by XCJT** [orbitdb/orbit-db#218]
I am using jsipfs + orbit-db

I tried to create a db as outlined:
```
const IPFS = require('ipfs')
const OrbitDB = require('orbit-db')

const ipfs = new IPFS()
const orbitdb = new OrbitDB(ipfs)
const docstore = orbitdb.docstore('db name')
```
This gave me an error - it said it was offline and a daemon needed to be started. So I used:
```
ipfs.on('ready', (e) => {
	const docstore = orbitdb.docstore('db name')
})
```

Now I get an error :
```
error: Unhandled Rejection at: Promise  Promise {                                                                                       
  <rejected> TypeError: Cannot read property 'listenerCount' of undefined                                                               
    at subscribe (/home/nmeadmin/cpxplane/node_modules/ipfs/src/core/components/pubsub.js:90:11)                                        
    at Promise (/home/nmeadmin/cpxplane/node_modules/ipfs/src/core/components/pubsub.js:23:11)                                          
    at Object.subscribe (/home/nmeadmin/cpxplane/node_modules/ipfs/src/core/components/pubsub.js:22:16)                                 
    at IPFSPubsub.subscribe (/home/nmeadmin/cpxplane/node_modules/orbit-db-pubsub/src/ipfs-pubsub.js:23:27)                             
    at OrbitDB._createStore (/home/nmeadmin/cpxplane/node_modules/orbit-db/src/OrbitDB.js:71:20)                                        
    at OrbitDB.docstore (/home/nmeadmin/cpxplane/node_modules/orbit-db/src/OrbitDB.js:41:17)                                            
    at IPFS.ipfs.on (/home/nmeadmin/cpxplane/src/ipfs/index.js:14:24)                                                                   
    at emitNone (events.js:86:13)                                                                                                       
    at IPFS.emit (events.js:188:7)                                                                                                      
    at done (/home/nmeadmin/cpxplane/node_modules/ipfs/src/core/boot.js:61:10) } TypeError: Cannot read property 'listenerCount' of unde
fined                                                                                                                                   
    at subscribe (/home/nmeadmin/cpxplane/node_modules/ipfs/src/core/components/pubsub.js:90:11)                                        
    at Promise (/home/nmeadmin/cpxplane/node_modules/ipfs/src/core/components/pubsub.js:23:11)                                          
    at Object.subscribe (/home/nmeadmin/cpxplane/node_modules/ipfs/src/core/components/pubsub.js:22:16)                                 
    at IPFSPubsub.subscribe (/home/nmeadmin/cpxplane/node_modules/orbit-db-pubsub/src/ipfs-pubsub.js:23:27)                             
    at OrbitDB._createStore (/home/nmeadmin/cpxplane/node_modules/orbit-db/src/OrbitDB.js:71:20)                                        
    at OrbitDB.docstore (/home/nmeadmin/cpxplane/node_modules/orbit-db/src/OrbitDB.js:41:17)                                            
    at IPFS.ipfs.on (/home/nmeadmin/cpxplane/src/ipfs/index.js:14:24)                                                                   
    at emitNone (events.js:86:13)                                                                                                       
    at IPFS.emit (events.js:188:7)                                                                                                      
    at done (/home/nmeadmin/cpxplane/node_modules/ipfs/src/core/boot.js:61:10)           
```

**Comment by cristiano-belloni** [comment]
Same here.

**Comment by shd101wyy** [comment]
Same here.

**Comment by haadcode** [comment]
This should be fixed now in [master](https://github.com/orbitdb/orbit-db) and latest version on [npm](https://www.npmjs.com/package/orbit-db). Let us know if this is still a problem.
