### ISSUE TITLE
Error during start on Windows 10

### ISSUE THREAD

**Issue by olegls2000** [orbitdb/orbit-db#263]
_Hi guys. I try to start pretty simple Node JS application with Orbit BD on Windows 10 and face with Error. Can anybody help me?_ 

**Precondition:**
OS: Windows10
Server: Node JS v.9.2.0
Files: 
package.json 
```
{
  "name": "test-ipfs",
  "version": "1.0.0",
  "description": "Desc",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "express": "^4.16.2",
    "ipfs": "^0.26.0",
    "orbit-db": "^0.18.2"
  }
}
```
app.js: 
```
var express = require('express');
var app = express();

var IPFS = require('ipfs');
var OrbitDB = require('orbit-db');
var ipfsOptions = {
  EXPERIMENTAL: {
    pubsub: true
  }
}
var ipfs = new IPFS(ipfsOptions);

ipfs.on('ready', async () => {
  const orbitdb = new OrbitDB(ipfs)
})

app.get('/', function (req, res) {
  res.send('HW!')
})

app.listen(3000, function () {
  console.log('Example app listening on port 3000!')
})
```
**Expected result:**
Application successfully run.
**Actual result:**
Error and stop the application.
Evidence:  
Log: 
```
S:\ProgramFilesSSD\node\node.exe --inspect-brk=50767 S:\orbit-test\app.js
Debugger listening on ws://127.0.0.1:50767/cd785dd0-f8ca-41c6-be04-82f6226581d2
For help see https://nodejs.org/en/docs/inspector
Example app listening on port 3000!
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/ipfs/QmYUDE83QHirhqGwUH2fc8xRBxbTzJtnRpidbEgPyBXzr1
Swarm listening on /ip4/10.0.75.1/tcp/4002/ipfs/QmYUDE83QHirhqGwUH2fc8xRBxbTzJtnRpidbEgPyBXzr1
Swarm listening on /ip4/192.168.0.14/tcp/4002/ipfs/QmYUDE83QHirhqGwUH2fc8xRBxbTzJtnRpidbEgPyBXzr1
Swarm listening on /ip4/127.0.0.1/tcp/4002/ipfs/QmYUDE83QHirhqGwUH2fc8xRBxbTzJtnRpidbEgPyBXzr1
Debugger attached.
S:\orbit-test\node_modules\ipfs-repo\node_modules\interface-datastore\src\key.js:45
      throw new Error(`Invalid key: ${this.toString()}`)
      ^

Error: Invalid key: /CIQPRU5S6XB2OALETECSFCCWTLBS745GTPY2GJANQBYTWCUDX2GCAVA
    at new Key (S:\orbit-test\node_modules\ipfs-repo\node_modules\interface-datastore\src\key.js:45:13)
    at keyFromBuffer (S:\orbit-test\node_modules\ipfs-repo\src\blockstore.js:20:10)
    at cidToDsKey (S:\orbit-test\node_modules\ipfs-repo\src\blockstore.js:30:10)
    at Object.has (S:\orbit-test\node_modules\ipfs-repo\src\blockstore.js:129:17)
    at each (S:\orbit-test\node_modules\ipfs-bitswap\src\decision-engine\index.js:207:23)
    at S:\orbit-test\node_modules\async\internal\withoutIndex.js:9:16
    at eachOfArrayLike (S:\orbit-test\node_modules\async\eachOf.js:65:9)
    at exports.default (S:\orbit-test\node_modules\async\eachOf.js:9:5)
    at eachLimit (S:\orbit-test\node_modules\async\each.js:80:24)
    at DecisionEngine._addWants (S:\orbit-test\node_modules\ipfs-bitswap\src\decision-engine\index.js:205:5)
Waiting for the debugger to disconnect...

Process finished with exit code 1
```

**Comment by haadcode** [comment]
Hi @olegls2000 and thanks for reporting this! I believe Windows is not fully supported yet :/

There are some issues open for js-ipfs on Windows: https://github.com/ipfs/js-ipfs/issues/1075 and https://github.com/ipfs/js-ipfs/issues/1074 and until then, I don't think OrbitDB will be able to support Windows.

Any help solving this and getting it supported would be highly appreciated, we definitely want to get it working on Windows too!

**Comment by richardschneider** [comment]
The release `ipfs 0.27.x` supports Windows.  Please upgrade to the latest IPFS and try again.

**Comment by haadcode** [comment]
That's great to hear @richardschneider! I don't access to a Windows machine right now so can't test it, but would appreciate any reports of success (or failure) running OrbitDB on Windows so that we can fix anything that is left to fix on OrbitDB side.

**Comment by aphelionz** [comment]
@richardschneider There's current windows support in a couple places:

1. PR here: https://github.com/orbitdb/orbit-db/pull/607
2. Npm package `orbit-db-win` is a _community_ package, not officially supported, but it might work.

Closing for now
