### ISSUE TITLE
Errors in Replicate

### ISSUE THREAD

**Issue by kidinamoto01** [orbitdb/orbit-db#271]
Hello @haadcode 

I tested the scripts for replicating databases, unfortunately I got the following error:
`Error: listen EADDRINUSE :::4003
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1476:7)
    at EventEmitter.emitter.listen [as _listen] (/Users/huangqing/Documents/work/orbit/demo/node_modules/pull-ws/server.js:53:12)
    at EventEmitter.listener.listen (/Users/huangqing/Documents/work/orbit/demo/node_modules/libp2p-websockets/src/listener.js:33:14)
    at /Users/huangqing/Documents/work/orbit/demo/node_modules/libp2p-swarm/src/transport.js:86:20
    at /Users/huangqing/node_modules/async/internal/parallel.js:31:39
    at eachOfArrayLike (/Users/huangqing/node_modules/async/eachOf.js:65:9)`

I am using jsipfs 0.26. Do I need more configurations?

Thanks for any advice.

**Comment by haadcode** [comment]
Hi @kidinamoto01, thanks for opening the issue!

I believe this error is due to two IPFS nodes trying to listen on the same port. When creating multiple IPFS nodes locally, options can be passed to the IPFS constructor. Here's an example:
```javascript
const ipfs = new IPFS({ 
  config: {
    Addresses: {
      API: '/ip4/127.0.0.1/tcp/0',
      Swarm: ['/ip4/0.0.0.0/tcp/0'],
      Gateway: '/ip4/0.0.0.0/tcp/0'
    },
  }
})
```

**The important line here is the one that says `Swarm: ['/ip4/0.0.0.0/tcp/0']`**. Note the `/0` at the end which tells IPFS to start the node using a random port.

By starting both/all local nodes with `/0`, ie. a random port, port collision at start is avoided and that should get both of the nodes up and running and communicating as expected.

Feel free to re-open the issue if this doesn't fix it for you!
