### ISSUE TITLE
Error message: Groups are not supported 

### ISSUE THREAD

**Issue by paulogr** [orbitdb/orbit-db#317]
Hi! I'm diving into orbit db and trying to understand the underhoods and saw this at the docs:
https://github.com/orbitdb/orbit-db/blob/master/GUIDE.md#manifest

It says that I can retreive the multihash part of my db address from IPFS. 
I tried many times and from a few different way but always get this:

```
Error: Groups are not supported
    at skip (/Users/paulogr/dev/projects/dstatuspage/dsporbitdb/node_modules/protons/src/compile/decode.js:193:13)
    at Object.decode (/Users/paulogr/dev/projects/dstatuspage/dsporbitdb/node_modules/protons/src/compile/decode.js:156:18)
```

I tried using ipfs.files.cat, ipfs.files.get from my own nodejs server and from my jsipfs daemon, always the same: *Groups are not supported*

Could, please, someone help with this?

Thank you!

**Comment by paulogr** [comment]
I see, it's a object not a a file.

Closing....
