### ISSUE TITLE
Error upon syncing

### ISSUE THREAD

**Issue by coyotespike** [orbitdb/orbit-db#337]
I started an orbit database on a remote Linux machine, and then hardcoded its ipfs address into my browser node's bootstrap list, as in #314 , and then had the browser node sync with the remote node's database.

The remote node then crashes, with error:
```
TypeError: callback is not a function
    at switch.dial (/pinningService/node_modules/libp2p/src/index.js:241:9)
    at Switch.dial (/pinningService/node_modules/libp2p-switch/src/dial.js:44:16)
    at _getPeerInfo (/pinningService/node_modules/libp2p/src/index.js:237:19)
    at Immediate.setImmediate (/pinningService/node_modules/libp2p/src/get-peer-info.js:
47:24)                                                                                 
    at runCallback (timers.js:757:18)
    at tryOnImmediate (timers.js:718:5)
    at processImmediate [as _immediateCallback] (timers.js:698:5)
 error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c node index.js
Directory: /<myProjectDirectory>
Output:
".
```

A console log in `node_modules/libp2p/source/index.js` revealed that the so-called callback ;-) is occasionally the string `ipfs-pubsub-room/v2`. This string seems to occur only in `node_modules/ipfs-pubsub-room/src/protocol.js`.

**Comment by coyotespike** [comment]
I was able to avoid the error by only calling the callback after confirming that it's a function, which makes me think the error doesn't come from my configuration.

**Comment by coyotespike** [comment]
This problem is in the process of being addressed elsewhere: https://github.com/ipfs-shipyard/ipfs-pubsub-room/pull/31

**Comment by haadcode** [comment]
@coyotespike FYI this was fixed in https://github.com/orbitdb/orbit-db/pull/340
