### ISSUE TITLE
Error in fetching data with ipfs-api

### ISSUE THREAD

**Issue by LuigiCerone** [orbitdb/orbit-db#446]
Hi,
I'm running a go-ipfs daemon on port 5001. 
If I try to run the following code:
```
const IpfsApi = require('ipfs-api');
const OrbitDB = require('orbit-db');

const ipfs = IpfsApi('localhost', '5001');
const orbitdb = new OrbitDB(ipfs);
let db = null;
orbitdb.docstore('test').then((data) => {
    db = data;
    db.put({_id: '12344', name: 'shamb0t', followers: 500}).then((hash) => {
        console.log(`Hash of inserted element: ${hash}`);

        console.log("1");
        ipfs.files.get(hash, function (err, files) {
            if (err)
                console.error(err);
            files.forEach((file) => {
                console.log(file.path);
                console.log(file.content.toString('utf8'));
            })
        });

        console.log("2");
        ipfs.files.cat(hash, function (err, file) {
            if (err) {
                console.error(err);
            }

            if (file !== undefined)
                console.log(file.toString('utf8'));
        })
    })
});
```

I get the following output:

``` Hash of inserted element: QmPE5dczESGpQ4ifTeGpiFec6UwGkypHif4PsqH6MHyivw
1
2
{ Error: proto: can't skip unknown wire type 6 for unixfs_pb.Data
    at parseError (/home/luigi-cer1/WebstormProjects/orbit_ipfs_test/node_modules/ipfs-api/src/utils/send-request.js:17:17)
    at ClientRequest.<anonymous> (/home/luigi-cer1/WebstormProjects/orbit_ipfs_test/node_modules/ipfs-api/src/utils/send-request.js:47:14)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
    at Socket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7) code: 0, type: 'error' }
```

If I try to access the information from the browser at http://localhost:5001/api/v0/object/get?arg=QmPE5dczESGpQ4ifTeGpiFec6UwGkypHif4PsqH6MHyivw I get:
```
{"Links":[],"Data":"{\"hash\":null,\"id\":\"/orbitdb/QmfSgLGvnAKwag7WRMNj2GoKbqqaKZgpb6vDtJRyRDMe9W/test\",\"payload\":{\"op\":\"PUT\",\"key\":\"12344\",\"value\":{\"_id\":\"12344\",\"name\":\"shamb0t\",\"followers\":500}},\"next\":[],\"v\":0,\"clock\":{\"id\":\"04698e3a816fe8590005686637383b18d1e7a63c03ce56c69f5f023c7afb88d49b7d71ec7710da8245451c282180e83b466212384aa9eb15b6cf2b7112ccf489a7\",\"time\":1},\"sig\":\"30440220308dbeecd3ad72579dc211478ecb52b494507e19b9ea5e4f48a74855a23d11e1022063a4b99365fdf6e4d1fd848b62320f9a3bb575fd0c1ae4dac5039acf0d47a20a\",\"key\":\"04698e3a816fe8590005686637383b18d1e7a63c03ce56c69f5f023c7afb88d49b7d71ec7710da8245451c282180e83b466212384aa9eb15b6cf2b7112ccf489a7\"}"}
```

Can anyone help me with this?
What I'm trying to do is store a JSON object into the orbit-db database and save the returned hash so I can then query ipfs by using its api and get my data back.
Thanks.

OS: Ubuntu 18.04.1 LTS
JS api: ipfs-api 24.0.1
orbit-db 0.19.9

**Comment by LuigiCerone** [comment]
I'm sorry, I should have used 
```
ipfs.object.data(hash, (err, data) => {
            if (err) {
                throw err
            }
            console.log(data.toString());
        })
```
