### ISSUE TITLE
DB's don't replicate but pubsub is working

### ISSUE THREAD

**Issue by lukas2005** [orbitdb/orbit-db#485]
So I'm running 2 nodes on a single machine with these swarm addresses:
```
Swarm listening on /ip6/::/tcp/4002/ipfs/QmdtoLsQdW5VPJFaj29XBfxbubqQCrJ9tobPjjZnzJEq4P
Swarm listening on /ip4/127.0.0.1/tcp/4002/ipfs/QmdtoLsQdW5VPJFaj29XBfxbubqQCrJ9tobPjjZnzJEq4P
Swarm listening on /ip4/192.168.0.108/tcp/4002/ipfs/QmdtoLsQdW5VPJFaj29XBfxbubqQCrJ9tobPjjZnzJEq4P
```
and
```
Swarm listening on /ip6/::/tcp/4003/ipfs/Qmagxhz1Lwe83eeys7YxAN3q1TPzGHu8jMjZkgMgtgt5mx
Swarm listening on /ip4/127.0.0.1/tcp/4003/ipfs/Qmagxhz1Lwe83eeys7YxAN3q1TPzGHu8jMjZkgMgtgt5mx
Swarm listening on /ip4/192.168.0.108/tcp/4003/ipfs/Qmagxhz1Lwe83eeys7YxAN3q1TPzGHu8jMjZkgMgtgt5mx
```
But the db's don't seem to be replicating between two of these nodes. I checked that pubsub is working (some parts of my app use it)

**Comment by lukas2005** [comment]
Not sure if this helps but here you have DEBUG output from my little client script that i wrote to test my API
Client 1:
```
[lukas2005@lukas2005-local API]$ node scripts/client.js
Create account or login? (C/l)c
I 1
Login: a
Password: a
Swarm listening on /dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star/ipfs/Qmb1owyHZhMQJ8ny1w8AYQNwyJLQCMwGABZQ59NhZLauTF
2018-10-28T10:25:13.945Z [DEBUG] orbit-db: open()
2018-10-28T10:25:13.945Z [DEBUG] orbit-db: Open database '/orbitdb/QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz/Anchor-Chat/userLog'
2018-10-28T10:25:13.945Z [DEBUG] orbit-db: Look from '.anchor1/.orbitdb'
2018-10-28T10:25:13.945Z [DEBUG] cache: load, database: /orbitdb/QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz/Anchor-Chat/userLog
2018-10-28T10:25:13.946Z [DEBUG] cache: open .anchor1/.orbitdb/QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz/Anchor-Chat/userLog
2018-10-28T10:25:14.080Z [DEBUG] orbit-db: Didn't find database '/orbitdb/QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz/Anchor-Chat/userLog'
2018-10-28T10:25:14.081Z [DEBUG] orbit-db: Loading Manifest for '/orbitdb/QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz/Anchor-Chat/userLog'
2018-10-28T10:25:24.706Z [DEBUG] orbit-db: Manifest for '/orbitdb/QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz/Anchor-Chat/userLog':
{
  "name": "Anchor-Chat/userLog",
  "type": "eventlog",
  "accessController": "/ipfs/QmX43NJHrfDCEdRo3LjQrmHwNJ9wL4bERkHeGBJwZmqQSo"
}
2018-10-28T10:25:24.707Z [DEBUG] cache: load, database: /orbitdb/QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz/Anchor-Chat/userLog
2018-10-28T10:25:24.708Z [DEBUG] orbit-db: Saved manifest to IPFS as 'QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz'
2018-10-28T10:25:25.109Z [DEBUG] cache: load, database: /orbitdb/QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz/Anchor-Chat/userLog
2018-10-28T10:25:25.118Z [DEBUG] pubsub: Topics open: 1
2018-10-28T10:25:25.120Z [DEBUG] orbit-db: open()
2018-10-28T10:25:25.120Z [DEBUG] orbit-db: Open database 'Anchor-Chat/a'
2018-10-28T10:25:25.120Z [DEBUG] orbit-db: Look from '.anchor1/.orbitdb'
2018-10-28T10:25:25.120Z [WARN]  orbit-db: Not a valid OrbitDB address 'Anchor-Chat/a', creating the database
2018-10-28T10:25:25.121Z [DEBUG] orbit-db: create()
2018-10-28T10:25:25.121Z [DEBUG] orbit-db: Creating database 'Anchor-Chat/a' as keyvalue in '.anchor1/.orbitdb'
2018-10-28T10:25:25.226Z [DEBUG] cache: load, database: /orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a
2018-10-28T10:25:25.226Z [DEBUG] cache: open .anchor1/.orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a
2018-10-28T10:25:25.337Z [DEBUG] cache: load, database: /orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a
2018-10-28T10:25:25.345Z [DEBUG] orbit-db: Saved manifest to IPFS as 'QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq'
2018-10-28T10:25:25.345Z [DEBUG] orbit-db: Created database '/orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a'
2018-10-28T10:25:25.345Z [DEBUG] orbit-db: open()
2018-10-28T10:25:25.345Z [DEBUG] orbit-db: Open database '/orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a'
2018-10-28T10:25:25.345Z [DEBUG] orbit-db: Look from '.anchor1/.orbitdb'
2018-10-28T10:25:25.345Z [DEBUG] cache: load, database: /orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a
2018-10-28T10:25:25.347Z [DEBUG] orbit-db: Found database '/orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a'
2018-10-28T10:25:25.348Z [DEBUG] orbit-db: Loading Manifest for '/orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a'
2018-10-28T10:25:25.352Z [DEBUG] orbit-db: Manifest for '/orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a':
{
  "name": "Anchor-Chat/a",
  "type": "keyvalue",
  "accessController": "/ipfs/QmXcU83A9in454AwZB1evTRvFxdDQbRSfLbMw2PTwKf5Ee"
}
2018-10-28T10:25:25.352Z [DEBUG] cache: load, database: /orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a
2018-10-28T10:25:25.352Z [DEBUG] orbit-db: Saved manifest to IPFS as 'QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq'
2018-10-28T10:25:25.354Z [DEBUG] cache: load, database: /orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a
2018-10-28T10:25:25.358Z [DEBUG] pubsub: Topics open: 2
Login of the person you want to talk with: 2018-10-28T10:25:55.138Z [DEBUG] pubsub: Peer joined /orbitdb/QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz/Anchor-Chat/userLog:
2018-10-28T10:25:55.138Z [DEBUG] pubsub: QmRuBLx1oPxiyYyB2K4BqmCJ3k3J8UGakYm3x4UiLqHAyi
2018-10-28T10:25:55.138Z [DEBUG] orbit-db: New peer 'QmRuBLx1oPxiyYyB2K4BqmCJ3k3J8UGakYm3x4UiLqHAyi' connected to '/orbitdb/QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz/Anchor-Chat/userLog'
2018-10-28T10:25:55.139Z [DEBUG] exchange-heads: Create a channel to QmRuBLx1oPxiyYyB2K4BqmCJ3k3J8UGakYm3x4UiLqHAyi
2018-10-28T10:25:55.145Z [DEBUG] exchange-heads: Channel created to QmRuBLx1oPxiyYyB2K4BqmCJ3k3J8UGakYm3x4UiLqHAyi
2018-10-28T10:25:55.513Z [DEBUG] orbit-db: Received 1 heads for '/orbitdb/QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz/Anchor-Chat/userLog':
 [
  "QmbKX4VvK5uwHxwxTg56EvEFkAYuEVaTzhhELgYc5vKjgh"
]
2018-10-28T10:25:55.513Z [DEBUG] orbit-db.store: Sync request #1 1
2018-10-28T10:25:55.565Z [DEBUG] orbit-db.store: Saved heads 2 [QmbKX4VvK5uwHxwxTg56EvEFkAYuEVaTzhhELgYc5vKjgh, QmYauNhKFG1Ryc8iobMFuudqqBpZPAhAfmLtzoEhPvTnsj]
2018-10-28T10:25:56.039Z [DEBUG] orbit-db: Received 1 heads for '/orbitdb/QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz/Anchor-Chat/userLog':
 [
  "QmbKX4VvK5uwHxwxTg56EvEFkAYuEVaTzhhELgYc5vKjgh"
]
2018-10-28T10:25:56.039Z [DEBUG] orbit-db.store: Sync request #2 1
2018-10-28T10:25:56.066Z [DEBUG] exchange-heads: Connected to QmRuBLx1oPxiyYyB2K4BqmCJ3k3J8UGakYm3x4UiLqHAyi
2018-10-28T10:25:56.066Z [DEBUG] exchange-heads: Send latest heads of '/orbitdb/QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz/Anchor-Chat/userLog':
 [
  "QmbKX4VvK5uwHxwxTg56EvEFkAYuEVaTzhhELgYc5vKjgh",
  "QmYauNhKFG1Ryc8iobMFuudqqBpZPAhAfmLtzoEhPvTnsj"
]
b
(node:32047) UnhandledPromiseRejectionWarning: Error: User doesn't exist!
    at AnchorAPI.<anonymous> (/home/lukas2005/Dokumenty/Projects/Anchor/API/dist/node/AnchorAPI.js:182:23)
    at Generator.next (<anonymous>)
    at /home/lukas2005/Dokumenty/Projects/Anchor/API/dist/node/AnchorAPI.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/lukas2005/Dokumenty/Projects/Anchor/API/dist/node/AnchorAPI.js:3:12)
    at AnchorAPI._getUserData (/home/lukas2005/Dokumenty/Projects/Anchor/API/dist/node/AnchorAPI.js:166:16)
    at AnchorAPI.<anonymous> (/home/lukas2005/Dokumenty/Projects/Anchor/API/dist/node/AnchorAPI.js:107:43)
    at Generator.next (<anonymous>)
    at fulfilled (/home/lukas2005/Dokumenty/Projects/Anchor/API/dist/node/AnchorAPI.js:4:58)
    at <anonymous>
(node:32047) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:32047) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2018-10-28T10:26:32.351Z [DEBUG] orbit-db: Received 0 heads for '/orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a':
 []
2018-10-28T10:26:32.424Z [DEBUG] pubsub: Peer joined /orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a:
2018-10-28T10:26:32.424Z [DEBUG] pubsub: QmRuBLx1oPxiyYyB2K4BqmCJ3k3J8UGakYm3x4UiLqHAyi
2018-10-28T10:26:32.424Z [DEBUG] orbit-db: New peer 'QmRuBLx1oPxiyYyB2K4BqmCJ3k3J8UGakYm3x4UiLqHAyi' connected to '/orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a'
2018-10-28T10:26:32.424Z [DEBUG] exchange-heads: Connected to QmRuBLx1oPxiyYyB2K4BqmCJ3k3J8UGakYm3x4UiLqHAyi
2018-10-28T10:26:32.424Z [DEBUG] exchange-heads: Send latest heads of '/orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a':
 [
  "Qme6o81kd38uri9cdNqW6VHfbZG7PQPPQcMkSowYrnbQ3T"
]
```
Client 2:
```
[lukas2005@lukas2005-local API]$ node scripts/client.jsCreate account or login? (C/l)c
I 2
Login: b
Password: b
Swarm listening on /dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star/ipfs/QmRuBLx1oPxiyYyB2K4BqmCJ3k3J8UGakYm3x4UiLqHAyi
2018-10-28T10:25:48.748Z [DEBUG] orbit-db: open()
2018-10-28T10:25:48.748Z [DEBUG] orbit-db: Open database '/orbitdb/QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz/Anchor-Chat/userLog'
2018-10-28T10:25:48.748Z [DEBUG] orbit-db: Look from '.anchor2/.orbitdb'
2018-10-28T10:25:48.749Z [DEBUG] cache: load, database: /orbitdb/QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz/Anchor-Chat/userLog
2018-10-28T10:25:48.749Z [DEBUG] cache: open .anchor2/.orbitdb/QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz/Anchor-Chat/userLog
2018-10-28T10:25:48.847Z [DEBUG] orbit-db: Didn't find database '/orbitdb/QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz/Anchor-Chat/userLog'
2018-10-28T10:25:48.847Z [DEBUG] orbit-db: Loading Manifest for '/orbitdb/QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz/Anchor-Chat/userLog'
2018-10-28T10:25:53.848Z [DEBUG] orbit-db: Manifest for '/orbitdb/QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz/Anchor-Chat/userLog':
{
  "name": "Anchor-Chat/userLog",
  "type": "eventlog",
  "accessController": "/ipfs/QmX43NJHrfDCEdRo3LjQrmHwNJ9wL4bERkHeGBJwZmqQSo"
}
2018-10-28T10:25:53.848Z [DEBUG] cache: load, database: /orbitdb/QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz/Anchor-Chat/userLog
2018-10-28T10:25:53.849Z [DEBUG] orbit-db: Saved manifest to IPFS as 'QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz'
2018-10-28T10:25:54.969Z [DEBUG] cache: load, database: /orbitdb/QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz/Anchor-Chat/userLog
2018-10-28T10:25:54.978Z [DEBUG] pubsub: Topics open: 1
2018-10-28T10:25:54.979Z [DEBUG] orbit-db: open()
2018-10-28T10:25:54.979Z [DEBUG] orbit-db: Open database 'Anchor-Chat/b'
2018-10-28T10:25:54.979Z [DEBUG] orbit-db: Look from '.anchor2/.orbitdb'
2018-10-28T10:25:54.979Z [WARN]  orbit-db: Not a valid OrbitDB address 'Anchor-Chat/b', creating the database
2018-10-28T10:25:54.979Z [DEBUG] orbit-db: create()
2018-10-28T10:25:54.979Z [DEBUG] orbit-db: Creating database 'Anchor-Chat/b' as keyvalue in '.anchor2/.orbitdb'
2018-10-28T10:25:55.081Z [DEBUG] cache: load, database: /orbitdb/QmTjpDT4ZWPmyKDfwCUXzC6RV2jmYBspfZEshu2zuEyn5W/Anchor-Chat/b
2018-10-28T10:25:55.081Z [DEBUG] cache: open .anchor2/.orbitdb/QmTjpDT4ZWPmyKDfwCUXzC6RV2jmYBspfZEshu2zuEyn5W/Anchor-Chat/b
2018-10-28T10:25:55.181Z [DEBUG] cache: load, database: /orbitdb/QmTjpDT4ZWPmyKDfwCUXzC6RV2jmYBspfZEshu2zuEyn5W/Anchor-Chat/b
2018-10-28T10:25:55.182Z [DEBUG] orbit-db: Saved manifest to IPFS as 'QmTjpDT4ZWPmyKDfwCUXzC6RV2jmYBspfZEshu2zuEyn5W'
2018-10-28T10:25:55.182Z [DEBUG] orbit-db: Created database '/orbitdb/QmTjpDT4ZWPmyKDfwCUXzC6RV2jmYBspfZEshu2zuEyn5W/Anchor-Chat/b'
2018-10-28T10:25:55.182Z [DEBUG] orbit-db: open()
2018-10-28T10:25:55.182Z [DEBUG] orbit-db: Open database '/orbitdb/QmTjpDT4ZWPmyKDfwCUXzC6RV2jmYBspfZEshu2zuEyn5W/Anchor-Chat/b'
2018-10-28T10:25:55.182Z [DEBUG] orbit-db: Look from '.anchor2/.orbitdb'
2018-10-28T10:25:55.182Z [DEBUG] cache: load, database: /orbitdb/QmTjpDT4ZWPmyKDfwCUXzC6RV2jmYBspfZEshu2zuEyn5W/Anchor-Chat/b
2018-10-28T10:25:55.183Z [DEBUG] orbit-db: Found database '/orbitdb/QmTjpDT4ZWPmyKDfwCUXzC6RV2jmYBspfZEshu2zuEyn5W/Anchor-Chat/b'
2018-10-28T10:25:55.183Z [DEBUG] orbit-db: Loading Manifest for '/orbitdb/QmTjpDT4ZWPmyKDfwCUXzC6RV2jmYBspfZEshu2zuEyn5W/Anchor-Chat/b'
2018-10-28T10:25:55.185Z [DEBUG] orbit-db: Manifest for '/orbitdb/QmTjpDT4ZWPmyKDfwCUXzC6RV2jmYBspfZEshu2zuEyn5W/Anchor-Chat/b':
{
  "name": "Anchor-Chat/b",
  "type": "keyvalue",
  "accessController": "/ipfs/QmX5zvaEDcQd94ByVSaR2BhCoJaBZf1M5noHAiGDXRQkgW"
}
2018-10-28T10:25:55.186Z [DEBUG] cache: load, database: /orbitdb/QmTjpDT4ZWPmyKDfwCUXzC6RV2jmYBspfZEshu2zuEyn5W/Anchor-Chat/b
2018-10-28T10:25:55.186Z [DEBUG] orbit-db: Saved manifest to IPFS as 'QmTjpDT4ZWPmyKDfwCUXzC6RV2jmYBspfZEshu2zuEyn5W'
2018-10-28T10:25:55.188Z [DEBUG] cache: load, database: /orbitdb/QmTjpDT4ZWPmyKDfwCUXzC6RV2jmYBspfZEshu2zuEyn5W/Anchor-Chat/b
2018-10-28T10:25:55.191Z [DEBUG] pubsub: Topics open: 2
Login of the person you want to talk with: 2018-10-28T10:25:55.978Z [DEBUG] pubsub: Peer joined /orbitdb/QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz/Anchor-Chat/userLog:
2018-10-28T10:25:55.978Z [DEBUG] pubsub: Qmb1owyHZhMQJ8ny1w8AYQNwyJLQCMwGABZQ59NhZLauTF
2018-10-28T10:25:55.978Z [DEBUG] orbit-db: New peer 'Qmb1owyHZhMQJ8ny1w8AYQNwyJLQCMwGABZQ59NhZLauTF' connected to '/orbitdb/QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz/Anchor-Chat/userLog'
2018-10-28T10:25:55.978Z [DEBUG] exchange-heads: Create a channel to Qmb1owyHZhMQJ8ny1w8AYQNwyJLQCMwGABZQ59NhZLauTF
2018-10-28T10:25:55.984Z [DEBUG] exchange-heads: Channel created to Qmb1owyHZhMQJ8ny1w8AYQNwyJLQCMwGABZQ59NhZLauTF
2018-10-28T10:25:55.987Z [DEBUG] exchange-heads: Connected to Qmb1owyHZhMQJ8ny1w8AYQNwyJLQCMwGABZQ59NhZLauTF
2018-10-28T10:25:55.987Z [DEBUG] exchange-heads: Send latest heads of '/orbitdb/QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz/Anchor-Chat/userLog':
 [
  "QmbKX4VvK5uwHxwxTg56EvEFkAYuEVaTzhhELgYc5vKjgh"
]
2018-10-28T10:25:56.114Z [DEBUG] orbit-db: Received 2 heads for '/orbitdb/QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz/Anchor-Chat/userLog':
 [
  "QmbKX4VvK5uwHxwxTg56EvEFkAYuEVaTzhhELgYc5vKjgh",
  "QmYauNhKFG1Ryc8iobMFuudqqBpZPAhAfmLtzoEhPvTnsj"
]
2018-10-28T10:25:56.114Z [DEBUG] orbit-db.store: Sync request #1 2
2018-10-28T10:25:56.182Z [DEBUG] orbit-db.store: Saved heads 2 [QmbKX4VvK5uwHxwxTg56EvEFkAYuEVaTzhhELgYc5vKjgh, QmYauNhKFG1Ryc8iobMFuudqqBpZPAhAfmLtzoEhPvTnsj]
a
2018-10-28T10:26:29.068Z [DEBUG] orbit-db: open()
2018-10-28T10:26:29.068Z [DEBUG] orbit-db: Open database '/orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a'
2018-10-28T10:26:29.068Z [DEBUG] orbit-db: Look from '.anchor2/.orbitdb'
2018-10-28T10:26:29.068Z [DEBUG] cache: load, database: /orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a
2018-10-28T10:26:29.069Z [DEBUG] cache: open .anchor2/.orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a
2018-10-28T10:26:29.184Z [DEBUG] orbit-db: Didn't find database '/orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a'
2018-10-28T10:26:29.184Z [DEBUG] orbit-db: Loading Manifest for '/orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a'
2018-10-28T10:26:29.635Z [DEBUG] orbit-db: Manifest for '/orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a':
{
  "name": "Anchor-Chat/a",
  "type": "keyvalue",
  "accessController": "/ipfs/QmXcU83A9in454AwZB1evTRvFxdDQbRSfLbMw2PTwKf5Ee"
}
2018-10-28T10:26:29.635Z [DEBUG] cache: load, database: /orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a
2018-10-28T10:26:29.635Z [DEBUG] orbit-db: Saved manifest to IPFS as 'QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq'
2018-10-28T10:26:31.300Z [DEBUG] cache: load, database: /orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a
2018-10-28T10:26:31.308Z [DEBUG] pubsub: Topics open: 3
(node:32124) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
    at Promise (/home/lukas2005/Dokumenty/Projects/Anchor/API/dist/node/AnchorAPI.js:138:29)
    at new Promise (<anonymous>)
    at AnchorAPI._getServerData (/home/lukas2005/Dokumenty/Projects/Anchor/API/dist/node/AnchorAPI.js:136:16)
    at User.<anonymous> (/home/lukas2005/Dokumenty/Projects/Anchor/API/dist/node/object/User.js:24:38)
    at Generator.next (<anonymous>)
    at /home/lukas2005/Dokumenty/Projects/Anchor/API/dist/node/object/User.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/lukas2005/Dokumenty/Projects/Anchor/API/dist/node/object/User.js:3:12)
    at User._init (/home/lukas2005/Dokumenty/Projects/Anchor/API/dist/node/object/User.js:20:16)
    at Function.<anonymous> (/home/lukas2005/Dokumenty/Projects/Anchor/API/dist/node/object/User.js:34:21)
(node:32124) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:32124) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2018-10-28T10:26:32.306Z [DEBUG] pubsub: Peer joined /orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a:
2018-10-28T10:26:32.307Z [DEBUG] pubsub: Qmb1owyHZhMQJ8ny1w8AYQNwyJLQCMwGABZQ59NhZLauTF
2018-10-28T10:26:32.307Z [DEBUG] orbit-db: New peer 'Qmb1owyHZhMQJ8ny1w8AYQNwyJLQCMwGABZQ59NhZLauTF' connected to '/orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a'
2018-10-28T10:26:32.307Z [DEBUG] exchange-heads: Connected to Qmb1owyHZhMQJ8ny1w8AYQNwyJLQCMwGABZQ59NhZLauTF
2018-10-28T10:26:32.307Z [DEBUG] exchange-heads: Send latest heads of '/orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a':
 []
2018-10-28T10:26:32.528Z [DEBUG] orbit-db: Received 1 heads for '/orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a':
 [
  "Qme6o81kd38uri9cdNqW6VHfbZG7PQPPQcMkSowYrnbQ3T"
]
2018-10-28T10:26:32.528Z [DEBUG] orbit-db.store: Sync request #1 1
2018-10-28T10:26:32.587Z [DEBUG] orbit-db.store: Saved heads 1 [Qme6o81kd38uri9cdNqW6VHfbZG7PQPPQcMkSowYrnbQ3T]
2018-10-28T10:26:33.081Z [DEBUG] orbit-db.store: Saved heads 1 [Qme6o81kd38uri9cdNqW6VHfbZG7PQPPQcMkSowYrnbQ3T]
2018-10-28T10:28:24.051Z [DEBUG] pubsub: Peer Qmb1owyHZhMQJ8ny1w8AYQNwyJLQCMwGABZQ59NhZLauTF left /orbitdb/QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz/Anchor-Chat/userLog
2018-10-28T10:28:24.348Z [DEBUG] pubsub: Peer Qmb1owyHZhMQJ8ny1w8AYQNwyJLQCMwGABZQ59NhZLauTF left /orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a
2018-10-28T10:28:28.057Z [DEBUG] pubsub: Peer joined /orbitdb/QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz/Anchor-Chat/userLog:
2018-10-28T10:28:28.057Z [DEBUG] pubsub: Qmb1owyHZhMQJ8ny1w8AYQNwyJLQCMwGABZQ59NhZLauTF
2018-10-28T10:28:28.057Z [DEBUG] orbit-db: New peer 'Qmb1owyHZhMQJ8ny1w8AYQNwyJLQCMwGABZQ59NhZLauTF' connected to '/orbitdb/QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz/Anchor-Chat/userLog'
2018-10-28T10:28:28.058Z [DEBUG] exchange-heads: Connected to Qmb1owyHZhMQJ8ny1w8AYQNwyJLQCMwGABZQ59NhZLauTF
2018-10-28T10:28:28.058Z [DEBUG] exchange-heads: Send latest heads of '/orbitdb/QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz/Anchor-Chat/userLog':
 [
  "QmbKX4VvK5uwHxwxTg56EvEFkAYuEVaTzhhELgYc5vKjgh",
  "QmYauNhKFG1Ryc8iobMFuudqqBpZPAhAfmLtzoEhPvTnsj"
]
2018-10-28T10:28:28.349Z [DEBUG] orbit-db: Received 2 heads for '/orbitdb/QmURvEErXCPnDB9ERPHRNHsChp44TGNNKnv8euRqa5n7Vz/Anchor-Chat/userLog':
 [
  "QmbKX4VvK5uwHxwxTg56EvEFkAYuEVaTzhhELgYc5vKjgh",
  "QmYauNhKFG1Ryc8iobMFuudqqBpZPAhAfmLtzoEhPvTnsj"
]
2018-10-28T10:28:28.349Z [DEBUG] orbit-db.store: Sync request #2 2
2018-10-28T10:28:28.351Z [DEBUG] pubsub: Peer joined /orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a:
2018-10-28T10:28:28.351Z [DEBUG] pubsub: Qmb1owyHZhMQJ8ny1w8AYQNwyJLQCMwGABZQ59NhZLauTF
2018-10-28T10:28:28.351Z [DEBUG] orbit-db: New peer 'Qmb1owyHZhMQJ8ny1w8AYQNwyJLQCMwGABZQ59NhZLauTF' connected to '/orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a'
2018-10-28T10:28:28.355Z [DEBUG] exchange-heads: Connected to Qmb1owyHZhMQJ8ny1w8AYQNwyJLQCMwGABZQ59NhZLauTF
2018-10-28T10:28:28.355Z [DEBUG] exchange-heads: Send latest heads of '/orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a':
 [
  "Qme6o81kd38uri9cdNqW6VHfbZG7PQPPQcMkSowYrnbQ3T"
]
2018-10-28T10:28:28.590Z [DEBUG] orbit-db: Received 1 heads for '/orbitdb/QmcoBUXNeVghDFdSGTjbwTyPiWW5ET1zPAwgbiVQE3Wcwq/Anchor-Chat/a':
 [
  "Qme6o81kd38uri9cdNqW6VHfbZG7PQPPQcMkSowYrnbQ3T"
]
2018-10-28T10:28:28.590Z [DEBUG] orbit-db.store: Sync request #2 1
```
(both on same machine)

**Comment by RichardLitt** [comment]
Sorry for not getting to this, @lukas2005. Did you resolve it?

**Comment by lukas2005** [comment]
Ah yeah turned out it was an issue on my part :)
