### ISSUE TITLE
bitswap:QmaqNE7F:error Failed to provide: DHT is not available

### ISSUE THREAD

**Issue by huhsame** [orbitdb/orbit-db#564]
I tried to apply oribitdb to my project.

I setup options of ipfs and database instance as same as official example do.

And I got this error.

 : DHT is not available
 : Unexpected end of input from reader
 : Channel destroyed
 : libp2p:floodsub:error Error: "/floodsub/1.0.0" not supported

I found the issue like this in js-ipfs.
[https://github.com/ipfs/js-ipfs/issues/967](https://github.com/ipfs/js-ipfs/issues/967)
It talked about gateway etc. 
after read it. I still cant find solution.

version
"ipfs": "^0.33.0",
 "orbit-db": "^0.19.9"

Here is my code. 

```
const ipfsOptions = {
    // repo: '/orbitdb/examples/browser/new/ipfs/0.27.3',
    start: true,
    EXPERIMENTAL: {
        pubsub: true,
    },
    config: {
        Addresses: {
            Swarm: [
                // Use IPFS dev signal server
                // '/dns4/star-signal.cloud.ipfs.team/wss/p2p-webrtc-star',
                '/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star',
                // Use local signal server
                // '/ip4/0.0.0.0/tcp/9090/wss/p2p-webrtc-star',
            ]
        },
    }
}

const orbitdbOptions = {
    // If database doesn't exist, create it
    create: true,
    overwrite: true,
    localOnly: false,
    write: ['*']
}

// Create IPFS instance
const ipfs = new IPFS(ipfsOptions)

ipfs.on('ready', async () => {
    const orbitdb = new OrbitDB(ipfs)
    const db = await orbitdb.docs('first-database', orbitdbOptions)
    console.log(db.address.toString())

    db.events.on('replicated', ( address )=>{
        console.log( address );
    })
})
```

![image](https://user-images.githubusercontent.com/9151382/52830644-f6215f80-3114-11e9-89bc-46aa4b9dbca1.png)

```
Swarm listening on /dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star/ipfs/QmaqNE7FqD4y4cFM4TqXpfULF418PmaAR1JecXMG97i8WV
browser.js:183 bitswap:QmaqNE7F:error Failed to provide: DHT is not available +0ms
browser.js:183 bitswap:QmaqNE7F:error Failed to provide: DHT is not available +6ms
oribit.js:42 /orbitdb/QmY9ccZDfq68ZYHQZpu3F5xiEXRUveBvdYjYaffq46FRjx/first-database
browser.js:183 mss:listener	:error (3avf6) Error: Unexpected end of input from reader.    at onComplete (http://localhost:8080/main.js:280584:35)    at Object.reader.read [as cb] (http://localhost:8080/main.js:280627:16)    at drain (http://localhost:8080/main.js:281259:23)    at http://localhost:8080/main.js:281276:18    at http://localhost:8080/main.js:281233:7    at http://localhost:8080/main.js:281327:13    at onNext (http://localhost:8080/main.js:280302:28)    at drain (http://localhost:8080/main.js:300907:18)    at Channel.<anonymous> (http://localhost:8080/main.js:300932:5)    at Channel.emit (http://localhost:8080/main.js:55116:7) +0ms
browser.js:183 mss:listener	:error (3avf6) Error: Channel destroyed    at Multiplex._push (http://localhost:8080/main.js:145240:23)    at Multiplex._write (http://localhost:8080/main.js:145305:12)    at doWrite (http://localhost:8080/main.js:143700:139)    at writeOrBuffer (http://localhost:8080/main.js:143689:5)    at Multiplex../node_modules/libp2p-mplex/node_modules/readable-stream/lib/_stream_writable.js.Writable.write (http://localhost:8080/main.js:143598:11)    at Stream.ondata (http://localhost:8080/main.js:300648:26)    at Stream.emit (http://localhost:8080/main.js:55111:5)    at next (http://localhost:8080/main.js:281589:13)    at http://localhost:8080/main.js:282382:9    at http://localhost:8080/main.js:281327:13 +1ms
```

**Comment by BartKnucle** [comment]
Can you try with an empty swarm?

**Comment by huhsame** [comment]
for entering your node to **DHT** .
should set bootstrap **as your node id.**
the address for bootstrap can be found at jsipfs config after jsipfs init.

```
config: {
    Addresses: {
        Swarm: ['/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star']
    },
    // this addr can be found at your jsipfs config after jsipfs init
    Bootstrap: ["/ip4/0.0.0.0/tcp/4002/ipfs/QmQiYfUkSWfu4jDtP2lkehfnsedlwXizLZ6ddw"]
}
```

**Comment by aphelionz** [comment]
@huhsame are you still experiencing this issue?

**Comment by huhsame** [comment]
nope. 
After adding my node id in bootstrap as I commented right above, it works.
Thanks for your comment.
