### ISSUE TITLE
preparations for js-ipfs 0.35

### ISSUE THREAD

**Issue by dirkmc** [orbitdb/orbit-db#589]
👋 I upgraded ipfs to v0.35.0-rc.4 and ran the tests but there were some failures.

It seems like some of them might be related to the EXPERIMENTAL.relay config, I've included the output below. Note that config validation has been tightened up, and relay is now configured at the root level.

You can read the release notes here: https://github.com/ipfs/js-ipfs/issues/1826

```
yarn run v1.13.0
$ TEST=all mocha


  orbit-db - Counters (js-ipfs)
    1) "before all" hook

  orbit-db - Counters (go-ipfs)
    counters
(node:3341) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
      ✓ creates and opens a database
      ✓ value is zero when it's a fresh database
      ✓ increases a counter value
      ✓ opens a saved counter
      ✓ syncs counters (2098ms)

  orbit-db - Create & Open (js-ipfs)
    2) "before all" hook

  orbit-db - Create & Open (go-ipfs)
2019-03-29T13:25:13.073Z [ERROR] pubsub: { Error: connect ECONNREFUSED 127.0.0.1:51148
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1083:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 51148 }
    Create
      Errors
        ✓ throws an error if given an invalid database type
        ✓ throws an error if given an address instead of name
        ✓ throws an error if database already exists
        ✓ throws an error if database type doesn't match
      Success
        ✓ creates a feed database
        ✓ database has the correct address
        ✓ saves the database locally
        ✓ saves database manifest reference locally
        ✓ saves database manifest file locally
        ✓ can pass local database directory as an option
        Access Controller
          ✓ creates an access controller and adds ourselves as writer by default
          ✓ creates an access controller and adds writers
          ✓ creates an access controller and doesn't add an admin
          ✓ creates an access controller and doesn't add read access keys
    determineAddress
      Errors
        ✓ throws an error if given an invalid database type
        ✓ throws an error if given an address instead of name
      Success
        ✓ does not save the address locally
        ✓ returns the address that would have been created
    Open
      ✓ throws an error if trying to open a database with name only and 'create' is not set to 'true'
      ✓ throws an error if trying to open a database with name only and 'create' is not set to true
      ✓ opens a database - name only
      ✓ opens the same database - from an address
      ✓ opens a database and adds the creator as the only writer
      ✓ doesn't open a database if we don't have it locally (901ms)
      ✓ throws an error if trying to open a database locally and we don't have it
      ✓ open the database and it has the added entries

  orbit-db - Create Custom Database Type (js-ipfs)
    3) "before all" hook

  orbit-db - Create Custom Database Type (go-ipfs)
    addDatabaseType
      ✓ should have the correct custom type
      ✓ cannot be overwritten

  orbit-db - Use a Custom Cache (js-ipfs)
    4) "before all" hook

  orbit-db - Use a Custom Cache (go-ipfs)
    allows orbit to use a custom cache with different store types
      ✓ eventlog allows custom keystore
      ✓ feed allows custom keystore
      ✓ key-value allows custom keystore
      ✓ documents allows custom keystore
      ✓ counter allows custom keystore

  orbit-db - Use a Custom Keystore (js-ipfs)
    5) "before all" hook

  orbit-db - Use a Custom Keystore (go-ipfs)
    allows orbit to use a custom keystore with different store types
      ✓ eventlog allows custom keystore
      ✓ feed allows custom keystore
      ✓ key-value allows custom keystore
      ✓ documents allows custom keystore
      ✓ counter allows custom keystore
    allows a custom keystore to be used with different store and write permissions
      ✓ eventlog allows custom keystore
      ✓ feed allows custom keystore
      ✓ key-value allows custom keystore
      ✓ documents allows custom keystore
      ✓ counter allows custom keystore

  orbit-db - Document Store (js-ipfs)
    6) "before all" hook

  orbit-db - Document Store (go-ipfs)
    ✓ creates and opens a database
    Default index '_id'
      ✓ put
      ✓ get - partial term match
      ✓ get after delete
      ✓ put updates a value
      ✓ query
      ✓ query after delete
      ✓ query returns full op
    Specified index
      ✓ put
      ✓ get - matches specified index

  orbit-db - Drop Database (js-ipfs)
    7) "before all" hook

  orbit-db - Drop Database (go-ipfs)
    Drop
      ✓ removes local database files

  orbit-db - Log Database (js-ipfs)
    8) "before all" hook

  orbit-db - Log Database (go-ipfs)
    Eventlog
      ✓ creates and opens a database
      ✓ returns 0 items when it's a fresh database
      ✓ returns the added entry's hash, 1 entry
      ✓ returns the added entry's hash, 2 entries
      ✓ adds five items
      ✓ adds an item that is > 256 bytes
    Iterator
      Defaults
        ✓ returns an iterator
        ✓ returns an item with the correct structure
        ✓ implements Iterator interface
        ✓ returns 1 item as default
        ✓ returns items in the correct order
      Collect
        ✓ returns all items
        ✓ returns 1 item
        ✓ returns 3 items
      Options: limit
        ✓ returns 1 item when limit is 0
        ✓ returns 1 item when limit is 1
        ✓ returns 3 items
        ✓ returns all items
        ✓ returns all items when limit is bigger than -1
        ✓ returns all items when limit is bigger than number of items
      Option: ranges
        gt & gte
          ✓ returns 1 item when gte is the head
          ✓ returns 0 items when gt is the head
          ✓ returns 2 item when gte is defined
          ✓ returns all items when gte is the root item
          ✓ returns items when gt is the root item
          ✓ returns items when gt is defined
        lt & lte
          ✓ returns one item after head when lt is the head
          ✓ returns all items when lt is head and limit is -1
          ✓ returns 3 items when lt is head and limit is 3
          ✓ returns null when lt is the root item
          ✓ returns one item when lte is the root item
          ✓ returns all items when lte is the head
          ✓ returns 3 items when lte is the head

  orbit-db - Feed Database (js-ipfs)
    9) "before all" hook

  orbit-db - Feed Database (go-ipfs)
    Feed
      ✓ creates and opens a database
      ✓ returns 0 items when it's a fresh database
      ✓ returns the added entry's hash, 1 entry
      ✓ returns the added entry's hash, 2 entries
      ✓ adds five items
      ✓ adds an item that is > 256 bytes
      ✓ deletes an item when only one item in the database
      ✓ deletes an item when two items in the database
      ✓ deletes an item between adds
    Iterator
      Defaults
        ✓ returns an iterator
        ✓ returns an item with the correct structure
        ✓ implements Iterator interface
        ✓ returns 1 item as default
        ✓ returns items in the correct order
      Collect
        ✓ returns all items
        ✓ returns 1 item
        ✓ returns 3 items
      Options: limit
        ✓ returns 1 item when limit is 0
        ✓ returns 1 item when limit is 1
        ✓ returns 3 items
        ✓ returns all items
        ✓ returns all items when limit is bigger than -1
        ✓ returns all items when limit is bigger than number of items
      Option: ranges
        gt & gte
          ✓ returns 1 item when gte is the head
          ✓ returns 0 items when gt is the head
          ✓ returns 2 item when gte is defined
          ✓ returns all items when gte is the root item
          ✓ returns items when gt is the root item
          ✓ returns items when gt is defined
        lt & lte
          ✓ returns one item after head when lt is the head
          ✓ returns all items when lt is head and limit is -1
          ✓ returns 3 items when lt is head and limit is 3
          ✓ returns null when lt is the root item
          ✓ returns one item when lte is the root item
          ✓ returns all items when lte is the head
          ✓ returns 3 items when lte is the head

  orbit-db - Key-Value Database (js-ipfs)
    10) "before all" hook

  orbit-db - Key-Value Database (go-ipfs)
    ✓ creates and opens a database
    ✓ put
    ✓ get
    ✓ put updates a value
    ✓ set is an alias for put
    ✓ put/get - multiple keys
    ✓ deletes a key
    ✓ deletes a key after multiple updates
    ✓ get - integer value
    ✓ get - object value
    ✓ get - array value

  orbit-db - Multiple Databases (js-ipfs)
    11) "before all" hook

  orbit-db - Multiple Databases (go-ipfs)
Creating databases and waiting for peers to connect
Peers connected
Writing to databases
Waiting for replication to finish
    ✓ replicates multiple open databases (2310ms)

  OrbitDB - Network Stress Tests
    - 1 update - 2 peers - as fast as possible
    - 32 update - concurrent - 2 peers - random interval
    - 1000 update concurrently - 2 peers - as fast as possible
    - 200 update as Buffers sequentially - 2 peers - as fast as possible
    - 50 update over a period long time - 6 peers - slow, random write intervals
    - 50 update over a period long time - 8 peers - slow, random write intervals

  orbit-db - OrbitDB Address (js-ipfs)
    12) "before all" hook

  orbit-db - OrbitDB Address (go-ipfs)
    Parse Address
      ✓ throws an error if address is empty
      ✓ parse address successfully
    isValid Address
      ✓ throws an error if address is empty
      ✓ validate address successfully
      ✓ handle missing orbitdb prefix
      ✓ handle missing db address name
      ✓ handle invalid multihash

  orbit-db - Persistency (js-ipfs)
    13) "before all" hook

  orbit-db - Persistency with custom cache (js-ipfs)
    14) "before all" hook

  orbit-db - Persistency (go-ipfs)
    load
      ✓ loads database from local cache
      ✓ loads database partially
      ✓ load and close several times (2051ms)
      ✓ closes database while loading
      ✓ load, add one, close - several times (2375ms)
      ✓ loading a database emits 'ready' event
      ✓ loading a database emits 'load.progress' event
    load from empty snapshot
      ✓ loads database from an empty snapshot
    load from snapshot
      ✓ loads database from snapshot
      ✓ load, add one and save snapshot several times (1191ms)
      ✓ throws an error when trying to load a missing snapshot
      ✓ loading a database emits 'ready' event
      ✓ loading a database emits 'load.progress' event

  orbit-db - Persistency with custom cache (go-ipfs)
    load
      ✓ loads database from local cache
      ✓ loads database partially
      ✓ load and close several times (1899ms)
      ✓ closes database while loading
      ✓ load, add one, close - several times (2260ms)
      ✓ loading a database emits 'ready' event
      ✓ loading a database emits 'load.progress' event
    load from empty snapshot
      ✓ loads database from an empty snapshot
    load from snapshot
      ✓ loads database from snapshot
      ✓ load, add one and save snapshot several times (1057ms)
      ✓ throws an error when trying to load a missing snapshot
      ✓ loading a database emits 'ready' event
      ✓ loading a database emits 'load.progress' event

  orbit-db - Replicate and Load (js-ipfs)
    15) "before all" hook

  orbit-db - Replicate and Load (go-ipfs)
2019-03-29T13:26:01.415Z [ERROR] pubsub: { Error: connect ECONNREFUSED 127.0.0.1:54910
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1083:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 54910 }
    two peers
Waiting for peers...
Found peers
      ✓ replicates database of 100 entries and loads it from the disk (2148ms)

  orbit-db - Automatic Replication (js-ipfs)
    16) "before all" hook

  orbit-db - Automatic Replication (go-ipfs)
    ✓ starts replicating the database when peers connect (1167ms)
    ✓ automatic replication exchanges the correct heads (1206ms)

  orbit-db - Replication (js-ipfs)
    17) "before all" hook

  orbit-db - Replication (go-ipfs)
    ✓ replicates database of 1 entry (1013ms)
    ✓ replicates database of 100 entries (1378ms)
    ✓ emits correct replication info (1245ms)
Writing 512 / 512 
Duration: 2791 ms
    ✓ emits correct replication info on fresh replication (4985ms)
    ✓ emits correct replication info in two-way replication (2139ms)

  orbit-db - Replication Status (js-ipfs)
    18) "before all" hook

  orbit-db - Replication Status (go-ipfs)
    ✓ has correct initial state
    ✓ has correct replication info after load
    ✓ has correct replication info after close
    ✓ has correct replication info after sync
    ✓ has correct replication info after loading from snapshot

  orbit-db - Write Permissions (js-ipfs)
    19) "before all" hook

  orbit-db - Write Permissions (go-ipfs)
    allows multiple peers to write to the databases
      ✓ eventlog allows multiple writers
      ✓ feed allows multiple writers
      ✓ key-value allows multiple writers
      ✓ documents allows multiple writers
      ✓ counter allows multiple writers
    syncs databases
      ✓ eventlog syncs
      ✓ feed syncs
      ✓ key-value syncs
      ✓ documents syncs
      ✓ counter syncs
    syncs databases that anyone can write to
      ✓ eventlog syncs
      ✓ feed syncs
      ✓ key-value syncs
      ✓ documents syncs
      ✓ counter syncs
    doesn't sync if peer is not allowed to write to the database
      ✓ eventlog doesn't sync
      ✓ feed doesn't sync
      ✓ key-value doesn't sync
      ✓ documents doesn't sync
      ✓ counter doesn't sync
    throws an error if peer is not allowed to write to the database
      ✓ eventlog throws an error
      ✓ feed throws an error
      ✓ key-value throws an error
      ✓ documents throws an error
      ✓ counter throws an error


  211 passing (1m)
  6 pending
  19 failing

  1) orbit-db - Counters (js-ipfs)
       "before all" hook:
     TypeError: Expected a value of type `{pubsub,ipnsPubsub,sharding,dht} | undefined` for `EXPERIMENTAL.relay` but received `{"enabled":false,"hop":{"enabled":false}}`.
      at Function.Struct.validate.value [as validate] (node_modules/superstruct/lib/index.js:1239:17)
      at Object.validate (node_modules/ipfs/src/core/config.js:77:39)
      at new IPFS (node_modules/ipfs/src/core/index.js:79:22)
      at new Node (node_modules/ipfsd-ctl/src/ipfsd-in-proc.js:67:17)
      at FactoryInProc.spawn (node_modules/ipfsd-ctl/src/factory-in-proc.js:134:18)
      at Promise (test/utils/start-ipfs.js:25:8)
      at new Promise (<anonymous>)
      at startIpfs (test/utils/start-ipfs.js:12:10)
      at Context.before (test/counterdb.test.js:36:22)

  2) orbit-db - Create & Open (js-ipfs)
       "before all" hook:
     TypeError: Expected a value of type `{pubsub,ipnsPubsub,sharding,dht} | undefined` for `EXPERIMENTAL.relay` but received `{"enabled":false,"hop":{"enabled":false}}`.
      at Function.Struct.validate.value [as validate] (node_modules/superstruct/lib/index.js:1239:17)
      at Object.validate (node_modules/ipfs/src/core/config.js:77:39)
      at new IPFS (node_modules/ipfs/src/core/index.js:79:22)
      at new Node (node_modules/ipfsd-ctl/src/ipfsd-in-proc.js:67:17)
      at FactoryInProc.spawn (node_modules/ipfsd-ctl/src/factory-in-proc.js:134:18)
      at Promise (test/utils/start-ipfs.js:25:8)
      at new Promise (<anonymous>)
      at startIpfs (test/utils/start-ipfs.js:12:10)
      at Context.before (test/create-open.test.js:35:21)

  3) orbit-db - Create Custom Database Type (js-ipfs)
       "before all" hook:
     TypeError: Expected a value of type `{pubsub,ipnsPubsub,sharding,dht} | undefined` for `EXPERIMENTAL.relay` but received `{"enabled":false,"hop":{"enabled":false}}`.
      at Function.Struct.validate.value [as validate] (node_modules/superstruct/lib/index.js:1239:17)
      at Object.validate (node_modules/ipfs/src/core/config.js:77:39)
      at new IPFS (node_modules/ipfs/src/core/index.js:79:22)
      at new Node (node_modules/ipfsd-ctl/src/ipfsd-in-proc.js:67:17)
      at FactoryInProc.spawn (node_modules/ipfsd-ctl/src/factory-in-proc.js:134:18)
      at Promise (test/utils/start-ipfs.js:25:8)
      at new Promise (<anonymous>)
      at startIpfs (test/utils/start-ipfs.js:12:10)
      at Context.before (test/create-type.test.js:40:21)

  4) orbit-db - Use a Custom Cache (js-ipfs)
       "before all" hook:
     TypeError: Expected a value of type `{pubsub,ipnsPubsub,sharding,dht} | undefined` for `EXPERIMENTAL.relay` but received `{"enabled":false,"hop":{"enabled":false}}`.
      at Function.Struct.validate.value [as validate] (node_modules/superstruct/lib/index.js:1239:17)
      at Object.validate (node_modules/ipfs/src/core/config.js:77:39)
      at new IPFS (node_modules/ipfs/src/core/index.js:79:22)
      at new Node (node_modules/ipfsd-ctl/src/ipfsd-in-proc.js:67:17)
      at FactoryInProc.spawn (node_modules/ipfsd-ctl/src/factory-in-proc.js:134:18)
      at Promise (test/utils/start-ipfs.js:25:8)
      at new Promise (<anonymous>)
      at startIpfs (test/utils/start-ipfs.js:12:10)
      at Context.before (test/custom-cache.test.js:30:21)

  5) orbit-db - Use a Custom Keystore (js-ipfs)
       "before all" hook:
     TypeError: Expected a value of type `{pubsub,ipnsPubsub,sharding,dht} | undefined` for `EXPERIMENTAL.relay` but received `{"enabled":false,"hop":{"enabled":false}}`.
      at Function.Struct.validate.value [as validate] (node_modules/superstruct/lib/index.js:1239:17)
      at Object.validate (node_modules/ipfs/src/core/config.js:77:39)
      at new IPFS (node_modules/ipfs/src/core/index.js:79:22)
      at new Node (node_modules/ipfsd-ctl/src/ipfsd-in-proc.js:67:17)
      at FactoryInProc.spawn (node_modules/ipfsd-ctl/src/factory-in-proc.js:134:18)
      at Promise (test/utils/start-ipfs.js:25:8)
      at new Promise (<anonymous>)
      at startIpfs (test/utils/start-ipfs.js:12:10)
      at Context.before (test/custom-keystore.test.js:29:21)

  6) orbit-db - Document Store (js-ipfs)
       "before all" hook:
     TypeError: Expected a value of type `{pubsub,ipnsPubsub,sharding,dht} | undefined` for `EXPERIMENTAL.relay` but received `{"enabled":false,"hop":{"enabled":false}}`.
      at Function.Struct.validate.value [as validate] (node_modules/superstruct/lib/index.js:1239:17)
      at Object.validate (node_modules/ipfs/src/core/config.js:77:39)
      at new IPFS (node_modules/ipfs/src/core/index.js:79:22)
      at new Node (node_modules/ipfsd-ctl/src/ipfsd-in-proc.js:67:17)
      at FactoryInProc.spawn (node_modules/ipfsd-ctl/src/factory-in-proc.js:134:18)
      at Promise (test/utils/start-ipfs.js:25:8)
      at new Promise (<anonymous>)
      at startIpfs (test/utils/start-ipfs.js:12:10)
      at Context.before (test/docstore.test.js:27:21)

  7) orbit-db - Drop Database (js-ipfs)
       "before all" hook:
     TypeError: Expected a value of type `{pubsub,ipnsPubsub,sharding,dht} | undefined` for `EXPERIMENTAL.relay` but received `{"enabled":false,"hop":{"enabled":false}}`.
      at Function.Struct.validate.value [as validate] (node_modules/superstruct/lib/index.js:1239:17)
      at Object.validate (node_modules/ipfs/src/core/config.js:77:39)
      at new IPFS (node_modules/ipfs/src/core/index.js:79:22)
      at new Node (node_modules/ipfsd-ctl/src/ipfsd-in-proc.js:67:17)
      at FactoryInProc.spawn (node_modules/ipfsd-ctl/src/factory-in-proc.js:134:18)
      at Promise (test/utils/start-ipfs.js:25:8)
      at new Promise (<anonymous>)
      at startIpfs (test/utils/start-ipfs.js:12:10)
      at Context.before (test/drop.test.js:31:21)

  8) orbit-db - Log Database (js-ipfs)
       "before all" hook:
     TypeError: Expected a value of type `{pubsub,ipnsPubsub,sharding,dht} | undefined` for `EXPERIMENTAL.relay` but received `{"enabled":false,"hop":{"enabled":false}}`.
      at Function.Struct.validate.value [as validate] (node_modules/superstruct/lib/index.js:1239:17)
      at Object.validate (node_modules/ipfs/src/core/config.js:77:39)
      at new IPFS (node_modules/ipfs/src/core/index.js:79:22)
      at new Node (node_modules/ipfsd-ctl/src/ipfsd-in-proc.js:67:17)
      at FactoryInProc.spawn (node_modules/ipfsd-ctl/src/factory-in-proc.js:134:18)
      at Promise (test/utils/start-ipfs.js:25:8)
      at new Promise (<anonymous>)
      at startIpfs (test/utils/start-ipfs.js:12:10)
      at Context.before (test/eventlog.test.js:31:21)

  9) orbit-db - Feed Database (js-ipfs)
       "before all" hook:
     TypeError: Expected a value of type `{pubsub,ipnsPubsub,sharding,dht} | undefined` for `EXPERIMENTAL.relay` but received `{"enabled":false,"hop":{"enabled":false}}`.
      at Function.Struct.validate.value [as validate] (node_modules/superstruct/lib/index.js:1239:17)
      at Object.validate (node_modules/ipfs/src/core/config.js:77:39)
      at new IPFS (node_modules/ipfs/src/core/index.js:79:22)
      at new Node (node_modules/ipfsd-ctl/src/ipfsd-in-proc.js:67:17)
      at FactoryInProc.spawn (node_modules/ipfsd-ctl/src/factory-in-proc.js:134:18)
      at Promise (test/utils/start-ipfs.js:25:8)
      at new Promise (<anonymous>)
      at startIpfs (test/utils/start-ipfs.js:12:10)
      at Context.before (test/feed.test.js:31:21)

  10) orbit-db - Key-Value Database (js-ipfs)
       "before all" hook:
     TypeError: Expected a value of type `{pubsub,ipnsPubsub,sharding,dht} | undefined` for `EXPERIMENTAL.relay` but received `{"enabled":false,"hop":{"enabled":false}}`.
      at Function.Struct.validate.value [as validate] (node_modules/superstruct/lib/index.js:1239:17)
      at Object.validate (node_modules/ipfs/src/core/config.js:77:39)
      at new IPFS (node_modules/ipfs/src/core/index.js:79:22)
      at new Node (node_modules/ipfsd-ctl/src/ipfsd-in-proc.js:67:17)
      at FactoryInProc.spawn (node_modules/ipfsd-ctl/src/factory-in-proc.js:134:18)
      at Promise (test/utils/start-ipfs.js:25:8)
      at new Promise (<anonymous>)
      at startIpfs (test/utils/start-ipfs.js:12:10)
      at Context.before (test/kvstore.test.js:28:21)

  11) orbit-db - Multiple Databases (js-ipfs)
       "before all" hook:
     TypeError: Expected a value of type `{pubsub,ipnsPubsub,sharding,dht} | undefined` for `EXPERIMENTAL.relay` but received `{"enabled":false,"hop":{"enabled":false}}`.
      at Function.Struct.validate.value [as validate] (node_modules/superstruct/lib/index.js:1239:17)
      at Object.validate (node_modules/ipfs/src/core/config.js:77:39)
      at new IPFS (node_modules/ipfs/src/core/index.js:79:22)
      at new Node (node_modules/ipfsd-ctl/src/ipfsd-in-proc.js:67:17)
      at FactoryInProc.spawn (node_modules/ipfsd-ctl/src/factory-in-proc.js:134:18)
      at Promise (test/utils/start-ipfs.js:25:8)
      at new Promise (<anonymous>)
      at startIpfs (test/utils/start-ipfs.js:12:10)
      at Context.before (test/multiple-databases.test.js:77:22)

  12) orbit-db - OrbitDB Address (js-ipfs)
       "before all" hook:
     TypeError: Expected a value of type `{pubsub,ipnsPubsub,sharding,dht} | undefined` for `EXPERIMENTAL.relay` but received `{"enabled":false,"hop":{"enabled":false}}`.
      at Function.Struct.validate.value [as validate] (node_modules/superstruct/lib/index.js:1239:17)
      at Object.validate (node_modules/ipfs/src/core/config.js:77:39)
      at new IPFS (node_modules/ipfs/src/core/index.js:79:22)
      at new Node (node_modules/ipfsd-ctl/src/ipfsd-in-proc.js:67:17)
      at FactoryInProc.spawn (node_modules/ipfsd-ctl/src/factory-in-proc.js:134:18)
      at Promise (test/utils/start-ipfs.js:25:8)
      at new Promise (<anonymous>)
      at startIpfs (test/utils/start-ipfs.js:12:10)
      at Context.before (test/orbit-db-address.test.js:28:21)

  13) orbit-db - Persistency (js-ipfs)
       "before all" hook:
     TypeError: Expected a value of type `{pubsub,ipnsPubsub,sharding,dht} | undefined` for `EXPERIMENTAL.relay` but received `{"enabled":false,"hop":{"enabled":false}}`.
      at Function.Struct.validate.value [as validate] (node_modules/superstruct/lib/index.js:1239:17)
      at Object.validate (node_modules/ipfs/src/core/config.js:77:39)
      at new IPFS (node_modules/ipfs/src/core/index.js:79:22)
      at new Node (node_modules/ipfsd-ctl/src/ipfsd-in-proc.js:67:17)
      at FactoryInProc.spawn (node_modules/ipfsd-ctl/src/factory-in-proc.js:134:18)
      at Promise (test/utils/start-ipfs.js:25:8)
      at new Promise (<anonymous>)
      at startIpfs (test/utils/start-ipfs.js:12:10)
      at Context.before (test/persistency.js:44:23)

  14) orbit-db - Persistency with custom cache (js-ipfs)
       "before all" hook:
     TypeError: Expected a value of type `{pubsub,ipnsPubsub,sharding,dht} | undefined` for `EXPERIMENTAL.relay` but received `{"enabled":false,"hop":{"enabled":false}}`.
      at Function.Struct.validate.value [as validate] (node_modules/superstruct/lib/index.js:1239:17)
      at Object.validate (node_modules/ipfs/src/core/config.js:77:39)
      at new IPFS (node_modules/ipfs/src/core/index.js:79:22)
      at new Node (node_modules/ipfsd-ctl/src/ipfsd-in-proc.js:67:17)
      at FactoryInProc.spawn (node_modules/ipfsd-ctl/src/factory-in-proc.js:134:18)
      at Promise (test/utils/start-ipfs.js:25:8)
      at new Promise (<anonymous>)
      at startIpfs (test/utils/start-ipfs.js:12:10)
      at Context.before (test/persistency.js:44:23)

  15) orbit-db - Replicate and Load (js-ipfs)
       "before all" hook:
     TypeError: Expected a value of type `{pubsub,ipnsPubsub,sharding,dht} | undefined` for `EXPERIMENTAL.relay` but received `{"enabled":false,"hop":{"enabled":false}}`.
      at Function.Struct.validate.value [as validate] (node_modules/superstruct/lib/index.js:1239:17)
      at Object.validate (node_modules/ipfs/src/core/config.js:77:39)
      at new IPFS (node_modules/ipfs/src/core/index.js:79:22)
      at new Node (node_modules/ipfsd-ctl/src/ipfsd-in-proc.js:67:17)
      at FactoryInProc.spawn (node_modules/ipfsd-ctl/src/factory-in-proc.js:134:18)
      at Promise (test/utils/start-ipfs.js:25:8)
      at new Promise (<anonymous>)
      at startIpfs (test/utils/start-ipfs.js:12:10)
      at Context.before (test/replicate-and-load.test.js:37:22)

  16) orbit-db - Automatic Replication (js-ipfs)
       "before all" hook:
     TypeError: Expected a value of type `{pubsub,ipnsPubsub,sharding,dht} | undefined` for `EXPERIMENTAL.relay` but received `{"enabled":false,"hop":{"enabled":false}}`.
      at Function.Struct.validate.value [as validate] (node_modules/superstruct/lib/index.js:1239:17)
      at Object.validate (node_modules/ipfs/src/core/config.js:77:39)
      at new IPFS (node_modules/ipfs/src/core/index.js:79:22)
      at new Node (node_modules/ipfsd-ctl/src/ipfsd-in-proc.js:67:17)
      at FactoryInProc.spawn (node_modules/ipfsd-ctl/src/factory-in-proc.js:134:18)
      at Promise (test/utils/start-ipfs.js:25:8)
      at new Promise (<anonymous>)
      at startIpfs (test/utils/start-ipfs.js:12:10)
      at Context.before (test/replicate-automatically.test.js:37:22)

  17) orbit-db - Replication (js-ipfs)
       "before all" hook:
     TypeError: Expected a value of type `{pubsub,ipnsPubsub,sharding,dht} | undefined` for `EXPERIMENTAL.relay` but received `{"enabled":false,"hop":{"enabled":false}}`.
      at Function.Struct.validate.value [as validate] (node_modules/superstruct/lib/index.js:1239:17)
      at Object.validate (node_modules/ipfs/src/core/config.js:77:39)
      at new IPFS (node_modules/ipfs/src/core/index.js:79:22)
      at new Node (node_modules/ipfsd-ctl/src/ipfsd-in-proc.js:67:17)
      at FactoryInProc.spawn (node_modules/ipfsd-ctl/src/factory-in-proc.js:134:18)
      at Promise (test/utils/start-ipfs.js:25:8)
      at new Promise (<anonymous>)
      at startIpfs (test/utils/start-ipfs.js:12:10)
      at Context.before (test/replicate.test.js:42:22)

  18) orbit-db - Replication Status (js-ipfs)
       "before all" hook:
     TypeError: Expected a value of type `{pubsub,ipnsPubsub,sharding,dht} | undefined` for `EXPERIMENTAL.relay` but received `{"enabled":false,"hop":{"enabled":false}}`.
      at Function.Struct.validate.value [as validate] (node_modules/superstruct/lib/index.js:1239:17)
      at Object.validate (node_modules/ipfs/src/core/config.js:77:39)
      at new IPFS (node_modules/ipfs/src/core/index.js:79:22)
      at new Node (node_modules/ipfsd-ctl/src/ipfsd-in-proc.js:67:17)
      at FactoryInProc.spawn (node_modules/ipfsd-ctl/src/factory-in-proc.js:134:18)
      at Promise (test/utils/start-ipfs.js:25:8)
      at new Promise (<anonymous>)
      at startIpfs (test/utils/start-ipfs.js:12:10)
      at Context.before (test/replication-status.test.js:37:21)

  19) orbit-db - Write Permissions (js-ipfs)
       "before all" hook:
     TypeError: Expected a value of type `{pubsub,ipnsPubsub,sharding,dht} | undefined` for `EXPERIMENTAL.relay` but received `{"enabled":false,"hop":{"enabled":false}}`.
      at Function.Struct.validate.value [as validate] (node_modules/superstruct/lib/index.js:1239:17)
      at Object.validate (node_modules/ipfs/src/core/config.js:77:39)
      at new IPFS (node_modules/ipfs/src/core/index.js:79:22)
      at new Node (node_modules/ipfsd-ctl/src/ipfsd-in-proc.js:67:17)
      at FactoryInProc.spawn (node_modules/ipfsd-ctl/src/factory-in-proc.js:134:18)
      at Promise (test/utils/start-ipfs.js:25:8)
      at new Promise (<anonymous>)
      at startIpfs (test/utils/start-ipfs.js:12:10)
      at Context.before (test/write-permissions.test.js:29:21)



error Command failed with exit code 19.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by oed** [comment]
I guess this can be closed :)

**Comment by RichardLitt** [comment]
@dirkmc 	These should be fixed now. :)
