### ISSUE TITLE
Npm install failing pretty spectacularly

### ISSUE THREAD

**Issue by DrawnWren** [orbitdb/orbit-db#646]
Steps to recreate:
Initialize empty npm project, ``npm i orbit-db ipfs``
Screen overflows with errors, but the end of the log is:
```
fatal error: too many errors emitted, stopping now [-ferror-limit=]
14 warnings and 20 errors generated.
make: *** [Release/obj.target/leveldown/src/batch.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/Cellar/node/12.4.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/wren/code/js/otest/node_modules/orbit-db-keystore/node_modules/leveldown
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN otest@1.0.0 No description
npm WARN otest@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@3.0.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@3.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wren/.npm/_logs/2019-06-18T04_52_49_149Z-debug.log
```

**Comment by phillmac** [comment]
What node version are you using?
Ive had simmilar framatic failures using anything greater than 11.13

**Comment by DrawnWren** [comment]
12.4

Should I downgrade?

It looks like it has something to do w/ the leveldown version used by orbit-db. Latest leveldown installs fine, but leveldown@3.0.2 fails spectacularly as well.

**Comment by phillmac** [comment]
Yeah I think that's going to be the quickest fix. Afaik the recomended
version is v10

**Comment by DrawnWren** [comment]
``nvm use --lts=dubnium`` fixed this.

**Comment by RichardLitt** [comment]
Glad you got that sorted. Thanks, @phillmac, for the help. :)
