### ISSUE TITLE
IPFS is not a constructor

### ISSUE THREAD

**Issue by simonbonnefoy** [orbitdb/orbit-db#846]
Hi, 
I have been trying to follow the [setup guide](https://github.com/orbitdb/orbit-db/blob/master/GUIDE.md#setup), 
however, when I run my script with nodejs, I always get the same error:
```
const ipfs = new IPFS(ipfsOptions)
             ^

TypeError: IPFS is not a constructor
    at Object.<anonymous> (/Users/simon/projects/orbitdb/example.js:11:14)
    at Module._compile (node:internal/modules/cjs/loader:1083:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:72:12)
    at node:internal/main/run_main_module:17:47
```

Here is my code 
``` javascript
const IPFS = require('ipfs')
const OrbitDB = require('orbit-db')

// Set ipfs options
const ipfsOptions = {
  EXPERIMENTAL: {
    pubsub: true
  }
}
// Create IPFS instance
const ipfs = new IPFS(ipfsOptions)

ipfs.on('ready', async () => {
  // Create OrbitDB instance
  const orbitdb = await OrbitDB.createInstance(ipfs)
})
```

And here is how I launch the script from terminal:
``` node example.js```

I have tried to investigate that error, but I am not sure how it relates to the Orbit-DB package.  
Is this a problem with the packaged I installed via npm, or should I add something into my script?

Thanks

**Comment by aphelionz** [comment]
Ah, sorry - sounds like we need to update the docs somewhere. try `const IPFS = await IPFS.create(opts)` instead

**Comment by simonbonnefoy** [comment]
Thanks for the quick reply. 
I also tried this way, but then it seems that there is a problem with the ```ipfs.on()``` function:
```
node example.js
Swarm listening on /ip4/127.0.0.1/tcp/4002/p2p/QmQ8HUJfbKDTR5otfPsHqST1yMrjnFDGRjAXmY3bBBYkZ7
Swarm listening on /ip4/192.168.5.136/tcp/4002/p2p/QmQ8HUJfbKDTR5otfPsHqST1yMrjnFDGRjAXmY3bBBYkZ7
Swarm listening on /ip4/192.168.47.1/tcp/4002/p2p/QmQ8HUJfbKDTR5otfPsHqST1yMrjnFDGRjAXmY3bBBYkZ7
Swarm listening on /ip4/192.168.199.1/tcp/4002/p2p/QmQ8HUJfbKDTR5otfPsHqST1yMrjnFDGRjAXmY3bBBYkZ7
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/p2p/QmQ8HUJfbKDTR5otfPsHqST1yMrjnFDGRjAXmY3bBBYkZ7
(node:43662) ExperimentalWarning: AbortController is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/simon/inatysco/projects/orbitdb/example.js:15
	ipfs.on('ready', async () => {
	     ^

TypeError: ipfs.on is not a function
    at main (/Users/simon/inatysco/projects/orbitdb/example.js:15:7)
```

And her is my new version of the code
``` javascript
const IPFS = require('ipfs')
const OrbitDB = require('orbit-db')

// Set ipfs options
const ipfsOptions = {
  EXPERIMENTAL: {
    pubsub: true
  }
}

async function main () {
	// Create IPFS instance
	const ipfs = await IPFS.create(ipfsOptions)

	ipfs.on('ready', async () => {

  		// Create OrbitDB instance
  		const orbitdb = await OrbitDB.createInstance(ipfs)
		})
}

main()
```

**Comment by aphelionz** [comment]
Yeah, once the await is done, it's equivalent to it being ready so you can just have your code be:

```JavaScript
const IPFS = require('ipfs')
const OrbitDB = require('orbit-db')

// Set ipfs options
const ipfsOptions = {
  EXPERIMENTAL: {
    pubsub: true
  }
}

async function main () {
	// Create IPFS instance
	const ipfs = await IPFS.create(ipfsOptions)
  	const orbitdb = await OrbitDB.createInstance(ipfs)
}

main()
```

**Comment by simonbonnefoy** [comment]
OK, that seems to work better. 
Thanks a lot
