### ISSUE TITLE
`OrbitDb.createInstance` fails because of call to deprecated `CID` method

### ISSUE THREAD

**Issue by gdethier** [orbitdb/orbit-db#904]
Calling `OrbitDb.createInstance(...)` currently fails with the following stack trace:

```
at CID.get toBaseEncodedString [as toBaseEncodedString] (.../node_modules/multiformats/cjs/src/cid.js:94:11)
    at Object.writeCbor [as write] (.../node_modules/orbit-db-access-controllers/node_modules/orbit-db-io/index.js:70:19)
    at IPFSAccessController.save (.../node_modules/orbit-db-access-controllers/src/ipfs-access-controller.js:46:13)
    at Function.create (.../node_modules/orbit-db-access-controllers/src/access-controllers.js:68:20)
    ...
```

`orbit-db`'s `orbit-db-access-controllers` dependency is relying on an obsolete version of `orbit-db-io` (see [this issue](https://github.com/orbitdb/orbit-db-access-controllers/issues/62)). Once linked issue is solved and a new version of `orbit-db-access-controllers` is released, `orbit-db`'s dependency should be upgraded.

**Comment by tabcat** [comment]
in the mean time you can try downgrading ipfs

**Comment by gdethier** [comment]
I am using `ipfs-core` dependency. Downgrading to version `0.8.0` indeed solves the problem.

**Comment by validityone** [comment]
Downgrading to `ipfs@0.54.x` also solves the problem for those using js ipfs

**Comment by CSDUMMI** [comment]
Is this [PR](https://github.com/orbitdb/orbit-db/pull/912) fixing this issue?

**Comment by gdethier** [comment]
@CSDUMMI This particular issue is solved by the PR, but not out-of-the-box. I had to add 2 dependencies: `@ipld/dag-cbor` and `@ipld/dag-pb`. The call to `OrbitDb.createInstance` now proceeds.

FYI, I have another error when calling `orbitdb.docs('...')` (`orbitdb` being the result of calling `OrbitDb.createInstance`):

```
Error: Invalid version, must be a number equal to 1 or 0
    at Function.validateCID (.../node_modules/cids/src/index.js:346:13)
    at new CID (.../node_modules/cids/src/index.js:174:9)
    at exports.cleanCid (.../node_modules/ipfs-core/src/components/block/utils.js:18:12)
    at get (.../node_modules/ipfs-core/src/components/block/get.js:16:11)
    at BlockAPI.get (.../node_modules/ipfs-core-utils/src/with-timeout-option.js:21:46)
    at Object.read (.../node_modules/orbit-db/node_modules/orbit-db-io/index.js:59:34)
    at OrbitDB.open (.../node_modules/orbit-db/src/OrbitDB.js:447:31)
    ...
```

But it is maybe unrelated to this particular issue.

**Comment by tabcat** [comment]
the newer ipfs versions are not supported yet. there will be a new release soon https://github.com/orbitdb/orbit-db/issues/913

**Comment by spartanz51** [comment]
> Downgrading to `ipfs@0.54.x` also solves the problem for those using js ipfs

I confirm that downgrading to ipfs@0.54.5 fixed the issue for me
