### ISSUE TITLE
Error: No binary available for arch 'undefined' (M1 Mac)

### ISSUE THREAD

**Issue by captaincole** [orbitdb/orbit-db#960]
When trying to run `npm install orbit-db@0.28.0` I ran into this error related to `go-ipfs`

```
npm ERR! command sh -c node src/post-install.js
npm ERR! https://dist.ipfs.io/go-ipfs/versions
npm ERR! Error: No binary available for arch 'undefined'
npm ERR!     at getDownloadURL (/Users/andrew/dweb/typed-orbit/node_modules/go-ipfs/src/download.js:162:11)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm ERR!     at async download (/Users/andrew/dweb/typed-orbit/node_modules/go-ipfs/src/download.js:178:15)
npm ERR!     at async module.exports (/Users/andrew/dweb/typed-orbit/node_modules/go-ipfs/src/download.js:251:13)
```

To solve this, I was able to set an environment variable (Which I found via this [this issue in npm-go-ipfs](https://github.com/ipfs/npm-go-ipfs/issues/46))

```
export TARGET_ARCH=arm64
```

**Comment by captaincole** [comment]
Asked and answered my own question above, but wanted to leave a trail for the next M1 Mac soul who runs into this issue.

**Comment by codeTIT4N** [comment]
it worked thankyou man @captaincole
