### ISSUE TITLE
OrbitDB 28.3 failing tests with go-ipfs@0.11 and ipfs-http-client@55

### ISSUE THREAD

**Issue by tabcat** [orbitdb/orbit-db#969]
There are two tests failing after upgrading to go-ipfs and ipfs-http-client

```
  1) orbit-db - ContractAccessController Integration (go-ipfs)
       OrbitDB Integration
         access controls
           granting access enables to write to the database:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/anders/Documents/dev/orbitdb/orbit-db/test/access-controllers/contract-access-controller-integration.test.js)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7)

  2) orbit-db - ContractAccessController Integration (go-ipfs)
       OrbitDB Integration
         access controls
           granting access enables to write to the database:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/anders/Documents/dev/orbitdb/orbit-db/test/access-controllers/contract-access-controller-integration.test.js)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7)
```

these two tests seem to timeout and may be related to the underlying cause of hanging in https://github.com/orbitdb/orbit-db/issues/967

**Comment by tabcat** [comment]
updating ipfs-http-client to v56 (latest) adds 2 more failures as timeouts

```
  3) orbit-db - Counters (go-ipfs)
       counters
         syncs counters:
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/anders/Documents/dev/orbitdb/orbit-db/test/counterdb.test.js)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7)

  4) orbit-db - Replicate and Load (go-ipfs)
       two peers
         "before all" hook for "replicates database of 100 entries and loads it from the disk":
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/anders/Documents/dev/orbitdb/orbit-db/test/replicate-and-load.test.js)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7)
```

**Comment by tabcat** [comment]
Looks like there are 4 separate test fails after upgrading go-ipfs to 0.12

```
  1) orbit-db - Create & Open (go-ipfs)
       Create
         Success
           loads cache from previous version of orbit-db:
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/anders/Documents/dev/orbitdb/orbit-db/test/create-open.test.js)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7)

  2) orbit-db - Create & Open (go-ipfs)
       Create
         Success
           loads cache from previous version of orbit-db with the directory option:
     Error: Database '/orbitdb/zdpuAzxo8oJKU9KsH2xE876aSBJsxPLU2G27o4m9unzjfnPZP/cache-schema-test2' already exists!
      at OrbitDB.create (src/OrbitDB.js:366:47)
      at Context.<anonymous> (test/create-open.test.js:183:16)

  3) orbit-db - Multiple Databases (go-ipfs)
       "before each" hook for "replicates multiple open databases":
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/anders/Documents/dev/orbitdb/orbit-db/test/multiple-databases.test.js)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7)

  4) orbit-db - Backward-Compatibility - Open & Load (go-ipfs)
       Open & Load - V1 entries
         "before all" hook for "open v1 orbitdb address":
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/anders/Documents/dev/orbitdb/orbit-db/test/v0-open-load.js)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7)
```

**Comment by tabcat** [comment]
Hopefully we can add support for both with a patch

**Comment by tabcat** [comment]
The failing tests seem to have most to do with timeouts related to replication. They are flaky in that they can fail or pass on a particular run. The replication tests have never been 100% solid in practice but it seems to have been increase with the upgrade (although this could just need more testing).
