### ISSUE TITLE
TimeoutError: request timed out 

### ISSUE THREAD

**Issue by zethuman** [orbitdb/orbit-db#972]
Hi, everyone!

Forced with problem replicating orbit db from mater node to peer node.

In peer node got an error 

```
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/p2p/12D3KooWRuoEQ4m89EidZZ38t5NL5AJNwtG1dSd71UbeawpTCLzf
[
  {
    addr: <Multiaddr 04c0a80152060fa2a50326002408011220bfc9c21953eb4e71563e9b85cedafd46e00d1e4679bfa5f93edac46bf3a9d056 - /ip4/192.xxx.1.xx/tcp/4002/p2p/12D3KooWNj2UWLvPtucttwfTXNbpWCd44suZKAvK8a9DcN6oCTrV>,
    peer: '12D3KooWNj2UWLvPtucttwfTXNbpWCd44suZKAvK8a9DcN6oCTrV',
    direction: 'outbound',
    muxer: '/mplex/6.7.0',
    latency: 'n/a',
    streams: []
  }
]
2022-03-07T10:57:09.991Z [DEBUG] orbit-db: open()
2022-03-07T10:57:09.991Z [DEBUG] orbit-db: Open database '/orbitdb/zdpuAztX5sy8NYSpRmbTjrFwKqBXPBeWgraxhB76g2HCRZJQQ/hub'
2022-03-07T10:57:09.993Z [DEBUG] orbit-db: Didn't find database '/orbitdb/zdpuAztX5sy8NYSpRmbTjrFwKqBXPBeWgraxhB76g2HCRZJQQ/hub'
2022-03-07T10:57:09.994Z [DEBUG] orbit-db: Loading Manifest for '/orbitdb/zdpuAztX5sy8NYSpRmbTjrFwKqBXPBeWgraxhB76g2HCRZJQQ/hub'
TimeoutError: request timed out
    at maybeThrowTimeoutError (D:\Source\Diploma\iprs-node\node_modules\ipfs-core-utils\cjs\src\with-timeout-option.js:35:15)
    at D:\Source\Diploma\iprs-node\node_modules\ipfs-core-utils\cjs\src\with-timeout-option.js:78:9
    at async Object.read (D:\Source\Diploma\iprs-node\node_modules\orbit-db-io\index.js:59:17)
    at async OrbitDB.open (D:\Source\Diploma\iprs-node\node_modules\orbit-db\src\OrbitDB.js:452:22)
    at async initOrbit (D:\Source\Diploma\iprs-node\services\orbitdb\index.js:47:20)
    at async initAll (D:\Source\Diploma\iprs-node\index.js:9:5) {
  code: 'ERR_TIMEOUT'
}
```
 
```
2022-03-07T10:27:05.381Z [DEBUG] orbit-db: open()
2022-03-07T10:27:05.382Z [DEBUG] orbit-db: Open database 'hub'
2022-03-07T10:27:05.383Z [WARN]  orbit-db: Not a valid OrbitDB address 'hub', creating the database
2022-03-07T10:27:05.383Z [DEBUG] orbit-db: create()
2022-03-07T10:27:05.384Z [DEBUG] orbit-db: Creating database 'hub' as keyvalue
2022-03-07T10:27:05.396Z [DEBUG] cache: cache: Set \orbitdb\zdpuAztX5sy8NYSpRmbTjrFwKqBXPBeWgraxhB76g2HCRZJQQ\hub\_manifest to zdpuAztX5sy8NYSpRmbTjrFwKqBXPBeWgraxhB76g2HCRZJQQ
2022-03-07T10:27:05.397Z [DEBUG] orbit-db: Saved manifest to IPFS as 'zdpuAztX5sy8NYSpRmbTjrFwKqBXPBeWgraxhB76g2HCRZJQQ'
2022-03-07T10:27:05.399Z [DEBUG] orbit-db: Created database '/orbitdb/zdpuAztX5sy8NYSpRmbTjrFwKqBXPBeWgraxhB76g2HCRZJQQ/hub'
2022-03-07T10:27:05.401Z [DEBUG] orbit-db: open()
2022-03-07T10:27:05.404Z [DEBUG] orbit-db: Open database '/orbitdb/zdpuAztX5sy8NYSpRmbTjrFwKqBXPBeWgraxhB76g2HCRZJQQ/hub'
2022-03-07T10:27:05.408Z [DEBUG] orbit-db: Found database '/orbitdb/zdpuAztX5sy8NYSpRmbTjrFwKqBXPBeWgraxhB76g2HCRZJQQ/hub'
2022-03-07T10:27:05.409Z [DEBUG] orbit-db: Loading Manifest for '/orbitdb/zdpuAztX5sy8NYSpRmbTjrFwKqBXPBeWgraxhB76g2HCRZJQQ/hub'
2022-03-07T10:27:05.419Z [DEBUG] orbit-db: Manifest for '/orbitdb/zdpuAztX5sy8NYSpRmbTjrFwKqBXPBeWgraxhB76g2HCRZJQQ/hub':
{
  "name": "hub",
  "type": "keyvalue",
  "accessController": "/ipfs/zdpuAsYRtJLLLDibnmxWPzyRGJEqtjmJP27ppKWcLreNGGTFN"
}
2022-03-07T10:27:05.422Z [DEBUG] cache: cache: Set \orbitdb\zdpuAztX5sy8NYSpRmbTjrFwKqBXPBeWgraxhB76g2HCRZJQQ\hub\_manifest to zdpuAztX5sy8NYSpRmbTjrFwKqBXPBeWgraxhB76g2HCRZJQQ
2022-03-07T10:27:05.423Z [DEBUG] orbit-db: Saved manifest to IPFS as 'zdpuAztX5sy8NYSpRmbTjrFwKqBXPBeWgraxhB76g2HCRZJQQ'
2022-03-07T10:27:05.431Z [DEBUG] pubsub: Topics open: 1
2022-03-07T10:27:05.492Z [DEBUG] cache: cache: Set \orbitdb\zdpuAztX5sy8NYSpRmbTjrFwKqBXPBeWgraxhB76g2HCRZJQQ\hub\_localHeads to [object Object]
world
Public database initialized /orbitdb/zdpuAztX5sy8NYSpRmbTjrFwKqBXPBeWgraxhB76g2HCRZJQQ/hub
```

Peer node code:

```
const ipfsOptions = {
    repo: './ipfs',
    start: true,
    EXPERIMENTAL: {
        pubsub: true
    },
    relay: {
        enabled: true,
        hop: {
            enabled: true,
        }
    }
}

const options = {
    accessController: {
        write: ["*"],
    },
    replicate: true,
    create: true,
    sync: true,
    localOnly: false,
    write: ["*"],
};

    const ipfs = await IPFS.create(ipfsOptions)
    await ipfs.bootstrap.add("/ip4/192.xxx.1.xx/tcp/4002/p2p/12D3KooWNj2UWLvPtucttwfTXNbpWCd44suZKAvK8a9DcN6oCTrV")
    await ipfs.swarm.connect("/ip4/192.xxx.1.xx/tcp/4002/p2p/12D3KooWNj2UWLvPtucttwfTXNbpWCd44suZKAvK8a9DcN6oCTrV")

    try {
        const orbitdb = new OrbitDB(ipfs, { directory: './orbitdb' })
        publicDB = await orbitdb.open("/orbitdb/zdpuAztX5sy8NYSpRmbTjrFwKqBXPBeWgraxhB76g2HCRZJQQ/hub", options)
        await publicDB.load()
        console.log(await publicDB.get('hello'))
    } catch (err) {
        console.log(err)
    }
```

Master node code:

```
const ipfsOptions = {
    repo: './ipfs',
    start: true,
    EXPERIMENTAL: {
        pubsub: true
    },
    relay: {
        enabled: true, 
        hop: {
            enabled: true
          }
      },
}

    let publicDB

    const ipfs = await IPFS.create(ipfsOptions)
    const orbitdb = await OrbitDB.createInstance(ipfs, { directory: './orbitdb' })
    publicDB = await orbitdb.keyvalue('hub', {accessController: { write: ['*']}})
    publicDB.load()
    await publicDB.put('hello', 'world')
    const res = await publicDB.get('hello')
    console.log(res)
    console.log("Public database initialized", publicDB.address.toString())
```

I understand that this is a network error, peer node can't find manifest for database from master node. 

Please hint me how can I decide it?

**Comment by tabcat** [comment]
you need to add configuration to ipfs/libp2p that would enable the ipfs node to fetch it.

**Comment by zethuman** [comment]
Solution: update node js to 16 lts.

However I forced with another problem, data that I post from peer node, does not replicated to master node

**Comment by zethuman** [comment]
Solution: update node js to 16 lts.
