### ISSUE TITLE
Access Controllers TypeError

### ISSUE THREAD

**Issue by eh-93** [orbitdb/orbit-db#981]
Hello - can anyone advise on this issue
I seem to be hitting this error message whenever defining custom access controls:

```
orbitdb (:|✔) node orbit.js
-> IPFS node connected
-> OrbitDB instance created
/Users/eh/Projects/orbitdb/node_modules/orbit-db-access-controllers/src/access-controllers.js:68
    const params = await ac.save()
                            ^

TypeError: Cannot read properties of undefined (reading 'save')
    at Function.create (/Users/eh/Projects/orbitdb/node_modules/orbit-db-access-controllers/src/access-controllers.js:68:29)
    at async OrbitDB._determineAddress (/Users/eh/Projects/orbitdb/node_modules/orbit-db/src/OrbitDB.js:336:37)
    at async OrbitDB.create (/Users/eh/Projects/orbitdb/node_modules/orbit-db/src/OrbitDB.js:359:23)

Node.js v17.3.0
```

Code snippet:
```
// import the packages
const IPFS = require('ipfs');
const OrbitDB = require('orbit-db');
const AccessControllers = require('orbit-db-access-controllers')

class OtherAccessController extends AccessControllers.AccessController {

    static get type() { return 'othertype' } // Return the type for this controller

    async canAppend(entry, identityProvider) {
        // logic to determine if entry can be added, for example:
        if (entry.payload === "hello world") {
            return true
        }
        console.log("Cannot append!")
        return false
    }
}

AccessControllers.addAccessController({ AccessController: OtherAccessController })

async function main() {
    const ipfs = await IPFS.create({
        preload: { enabled: false },
        repo: './ipfs',
        EXPERIMENTAL: { pubsub: true },
        config: {
            Bootstrap: [],
            Addresses: { Swarm: [] }
        }
    });
    console.log('-> IPFS node connected');
    const orbitdb = await OrbitDB.createInstance(ipfs, { AccessControllers: AccessControllers });
    console.log('-> OrbitDB instance created');


    const db1 = await orbitdb.keyvalue('pet-animal-secure3', {
        accessController: {
            type: 'othertype', write: [orbitdb.identity.id]
        }
    });
    const res = await db1.put('species', 'German Shepherd', { pin: true });
    console.log(res)
    await db1.put('owner', 'myself', { pin: true });
    console.log('-> One pet animal created');
    await db1.close();

    // 2nd stage, reopen and retrieve from the database
    const db2 = await orbitdb.keyvalue('pet-animal-secure3');
    await db2.load();
    let species = db2.get('species');
    console.log(' -> database value of "species" = ', species);
    let owner = db2.get('owner');
    console.log(' -> database value of "owner" = ', owner);
    await db2.close();
}
main();
```

Using:
```
    "ipfs": "^0.62.1",
    "orbit-db": "^0.28.3",
    "orbit-db-access-controllers": "^0.3.2"
```

**Comment by tabcat** [comment]
looks like this is an issue with the docs or the access controller interface.

ac returned by create method: https://github.com/orbitdb/orbit-db-access-controllers/blob/bf06527fc75d542460428a185fc83092a2523197/src/access-controllers.js#L67-L68

create method is no-op by default: https://github.com/orbitdb/orbit-db-access-controllers/blob/bf06527fc75d542460428a185fc83092a2523197/src/access-controller-interface.js#L16

no documented override: https://github.com/orbitdb/orbit-db-access-controllers#creating-a-custom-access-controller

wondering if its better to document or add a basic working create method to the interface...

**Comment by eh-93** [comment]
Managed to get it working by overriding the create method. Docs a little misleading.
